export interface GIEntry { gi: number; confidence: number; source: string; }

export const GI_DATABASE: Record<string, GIEntry> = {
  // ── TÜRK MUTFAĞI ──────────────────────────────────────────────
  "beyaz ekmek": { gi: 75, confidence: 0.95, source: "Sydney GI DB" },
  "tam buğday ekmeği": { gi: 51, confidence: 0.92, source: "Sydney GI DB" },
  "çavdar ekmeği": { gi: 41, confidence: 0.90, source: "Sydney GI DB" },
  "simit": { gi: 68, confidence: 0.80, source: "TürKomp" },
  "poğaça": { gi: 62, confidence: 0.75, source: "TürKomp" },
  "açma": { gi: 65, confidence: 0.72, source: "TürKomp" },
  "bulgur pilavı": { gi: 46, confidence: 0.88, source: "Sydney GI DB" },
  "pirinç pilavı": { gi: 64, confidence: 0.90, source: "Sydney GI DB" },
  "mercimek çorbası": { gi: 44, confidence: 0.85, source: "TürKomp" },
  "ezogelin çorbası": { gi: 42, confidence: 0.80, source: "TürKomp" },
  "tarhana çorbası": { gi: 45, confidence: 0.75, source: "TürKomp" },
  "kırmızı mercimek": { gi: 29, confidence: 0.95, source: "Sydney GI DB" },
  "yeşil mercimek": { gi: 30, confidence: 0.92, source: "Sydney GI DB" },
  "kuru fasulye": { gi: 29, confidence: 0.92, source: "Sydney GI DB" },
  "nohut": { gi: 28, confidence: 0.92, source: "Sydney GI DB" },
  "döner": { gi: 35, confidence: 0.70, source: "TürKomp" },
  "köfte": { gi: 10, confidence: 0.75, source: "TürKomp" },
  "kebap": { gi: 5, confidence: 0.80, source: "TürKomp" },
  "adana kebap": { gi: 5, confidence: 0.80, source: "TürKomp" },
  "urfa kebap": { gi: 5, confidence: 0.80, source: "TürKomp" },
  "şiş kebap": { gi: 5, confidence: 0.82, source: "TürKomp" },
  "tavuk ızgara": { gi: 0, confidence: 0.99, source: "Genel" },
  "tavuk döner": { gi: 30, confidence: 0.72, source: "TürKomp" },
  "mantı": { gi: 52, confidence: 0.75, source: "TürKomp" },
  "börek": { gi: 60, confidence: 0.72, source: "TürKomp" },
  "su böreği": { gi: 58, confidence: 0.72, source: "TürKomp" },
  "sigara böreği": { gi: 62, confidence: 0.70, source: "TürKomp" },
  "lahmacun": { gi: 62, confidence: 0.74, source: "TürKomp" },
  "pide": { gi: 70, confidence: 0.78, source: "TürKomp" },
  "kasarlı pide": { gi: 65, confidence: 0.75, source: "TürKomp" },
  "gözleme": { gi: 58, confidence: 0.72, source: "TürKomp" },
  "baklava": { gi: 55, confidence: 0.80, source: "TürKomp" },
  "künefe": { gi: 58, confidence: 0.70, source: "TürKomp" },
  "sütlaç": { gi: 55, confidence: 0.75, source: "TürKomp" },
  "aşure": { gi: 48, confidence: 0.70, source: "TürKomp" },
  "kazandibi": { gi: 52, confidence: 0.70, source: "TürKomp" },
  "halva": { gi: 60, confidence: 0.75, source: "TürKomp" },
  "helva": { gi: 60, confidence: 0.75, source: "TürKomp" },
  "patates haşlama": { gi: 78, confidence: 0.95, source: "Sydney GI DB" },
  "patates kızartma": { gi: 63, confidence: 0.90, source: "Sydney GI DB" },
  "yoğurt": { gi: 36, confidence: 0.92, source: "Sydney GI DB" },
  "ayran": { gi: 30, confidence: 0.85, source: "TürKomp" },
  "karnıyarık": { gi: 38, confidence: 0.72, source: "TürKomp" },
  "dolma": { gi: 55, confidence: 0.72, source: "TürKomp" },
  "sarma": { gi: 50, confidence: 0.70, source: "TürKomp" },
  "zeytinyağlı fasulye": { gi: 35, confidence: 0.75, source: "TürKomp" },
  "imam bayıldı": { gi: 30, confidence: 0.70, source: "TürKomp" },
  "türk lokumu": { gi: 65, confidence: 0.78, source: "TürKomp" },
  "çorba": { gi: 32, confidence: 0.70, source: "TürKomp" },
  "makarna": { gi: 49, confidence: 0.90, source: "Sydney GI DB" },
  "pilav": { gi: 64, confidence: 0.88, source: "TürKomp" },
  "menemen": { gi: 25, confidence: 0.78, source: "TürKomp" },
  "çılbır": { gi: 20, confidence: 0.75, source: "TürKomp" },
  "mücver": { gi: 45, confidence: 0.72, source: "TürKomp" },
  "mercimek köftesi": { gi: 32, confidence: 0.78, source: "TürKomp" },
  "humus": { gi: 28, confidence: 0.90, source: "Sydney GI DB" },
  "cacık": { gi: 20, confidence: 0.80, source: "TürKomp" },
  "haydari": { gi: 20, confidence: 0.75, source: "TürKomp" },
  "tarator": { gi: 18, confidence: 0.72, source: "TürKomp" },
  "çiğ köfte": { gi: 52, confidence: 0.72, source: "TürKomp" },
  "kısır": { gi: 46, confidence: 0.75, source: "TürKomp" },
  "meyhane mezesi": { gi: 30, confidence: 0.65, source: "TürKomp" },
  "türk kahvesi": { gi: 0, confidence: 0.99, source: "Genel" },
  "çay": { gi: 0, confidence: 0.99, source: "Genel" },
  "salep": { gi: 55, confidence: 0.72, source: "TürKomp" },
  "boza": { gi: 50, confidence: 0.70, source: "TürKomp" },
  "şalgam": { gi: 8, confidence: 0.75, source: "TürKomp" },

  // ── EKMEK & TAHIL ─────────────────────────────────────────────
  "baguette": { gi: 95, confidence: 0.92, source: "Sydney GI DB" },
  "croissant": { gi: 67, confidence: 0.85, source: "Sydney GI DB" },
  "naan": { gi: 71, confidence: 0.85, source: "Sydney GI DB" },
  "chapati": { gi: 52, confidence: 0.85, source: "Sydney GI DB" },
  "roti": { gi: 54, confidence: 0.85, source: "Sydney GI DB" },
  "tortilla": { gi: 52, confidence: 0.88, source: "Sydney GI DB" },
  "mısır ekmeği": { gi: 69, confidence: 0.85, source: "Sydney GI DB" },
  "pita ekmeği": { gi: 57, confidence: 0.88, source: "Sydney GI DB" },
  "pumpernickel": { gi: 41, confidence: 0.88, source: "Sydney GI DB" },
  "waffle": { gi: 76, confidence: 0.85, source: "Sydney GI DB" },
  "pancake": { gi: 67, confidence: 0.85, source: "Sydney GI DB" },
  "bagel": { gi: 72, confidence: 0.88, source: "Sydney GI DB" },
  "muffin": { gi: 62, confidence: 0.82, source: "Sydney GI DB" },

  // ── PİRİNÇ ÇEŞİTLERİ ──────────────────────────────────────────
  "beyaz pirinç": { gi: 73, confidence: 0.95, source: "Sydney GI DB" },
  "esmer pirinç": { gi: 55, confidence: 0.92, source: "Sydney GI DB" },
  "basmati pirinç": { gi: 52, confidence: 0.92, source: "Sydney GI DB" },
  "jasmine rice": { gi: 68, confidence: 0.90, source: "Sydney GI DB" },
  "sushi rice": { gi: 72, confidence: 0.88, source: "Sydney GI DB" },
  "sushi pirinci": { gi: 72, confidence: 0.88, source: "Sydney GI DB" },
  "glutinous rice": { gi: 98, confidence: 0.85, source: "Sydney GI DB" },
  "wild rice": { gi: 57, confidence: 0.85, source: "Sydney GI DB" },

  // ── TAHILLAR & YULAF ──────────────────────────────────────────
  "yulaf ezmesi": { gi: 55, confidence: 0.95, source: "Sydney GI DB" },
  "oatmeal": { gi: 55, confidence: 0.95, source: "Sydney GI DB" },
  "granola": { gi: 45, confidence: 0.85, source: "Sydney GI DB" },
  "mısır gevreği": { gi: 81, confidence: 0.92, source: "Sydney GI DB" },
  "corn flakes": { gi: 81, confidence: 0.92, source: "Sydney GI DB" },
  "quinoa": { gi: 53, confidence: 0.90, source: "Sydney GI DB" },
  "kinoa": { gi: 53, confidence: 0.90, source: "Sydney GI DB" },
  "arpa": { gi: 28, confidence: 0.90, source: "Sydney GI DB" },
  "darı": { gi: 71, confidence: 0.80, source: "Sydney GI DB" },
  "karabuğday": { gi: 51, confidence: 0.85, source: "Sydney GI DB" },
  "amaranth": { gi: 35, confidence: 0.80, source: "Sydney GI DB" },

  // ── MAKARNA ÇEŞİTLERİ ─────────────────────────────────────────
  "spaghetti": { gi: 49, confidence: 0.95, source: "Sydney GI DB" },
  "fettuccine": { gi: 32, confidence: 0.90, source: "Sydney GI DB" },
  "linguine": { gi: 46, confidence: 0.90, source: "Sydney GI DB" },
  "penne": { gi: 50, confidence: 0.90, source: "Sydney GI DB" },
  "rigatoni": { gi: 51, confidence: 0.88, source: "Sydney GI DB" },
  "tam buğday makarna": { gi: 37, confidence: 0.92, source: "Sydney GI DB" },
  "erişte": { gi: 35, confidence: 0.85, source: "Sydney GI DB" },
  "ramen noodle": { gi: 73, confidence: 0.85, source: "Sydney GI DB" },
  "udon": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "soba": { gi: 46, confidence: 0.88, source: "Sydney GI DB" },
  "rice noodle": { gi: 61, confidence: 0.88, source: "Sydney GI DB" },
  "glass noodle": { gi: 39, confidence: 0.85, source: "Sydney GI DB" },

  // ── İTALYAN MUTFAĞI ───────────────────────────────────────────
  "pizza": { gi: 60, confidence: 0.85, source: "Sydney GI DB" },
  "margherita pizza": { gi: 60, confidence: 0.85, source: "Sydney GI DB" },
  "lasagna": { gi: 47, confidence: 0.82, source: "Sydney GI DB" },
  "lasagne": { gi: 47, confidence: 0.82, source: "Sydney GI DB" },
  "risotto": { gi: 69, confidence: 0.82, source: "Sydney GI DB" },
  "gnocchi": { gi: 68, confidence: 0.82, source: "Sydney GI DB" },
  "tiramisu": { gi: 45, confidence: 0.75, source: "IJGI" },
  "gelato": { gi: 42, confidence: 0.78, source: "IJGI" },
  "bruschetta": { gi: 68, confidence: 0.78, source: "IJGI" },
  "carbonara": { gi: 45, confidence: 0.78, source: "IJGI" },

  // ── ASYA MUTFAĞI (GENEL) ──────────────────────────────────────
  "fried rice": { gi: 77, confidence: 0.88, source: "Sydney GI DB" },
  "kızarmış pirinç": { gi: 77, confidence: 0.88, source: "Sydney GI DB" },
  "pad thai": { gi: 60, confidence: 0.80, source: "IJGI" },
  "spring roll": { gi: 55, confidence: 0.78, source: "IJGI" },
  "bahar rulo": { gi: 55, confidence: 0.78, source: "IJGI" },
  "dim sum": { gi: 50, confidence: 0.75, source: "IJGI" },
  "dumplings": { gi: 50, confidence: 0.78, source: "IJGI" },

  // ── JAPON MUTFAĞI ─────────────────────────────────────────────
  "sushi": { gi: 55, confidence: 0.88, source: "Sydney GI DB" },
  "sashimi": { gi: 0, confidence: 0.95, source: "Genel" },
  "ramen": { gi: 68, confidence: 0.85, source: "IJGI" },
  "tempura": { gi: 45, confidence: 0.78, source: "IJGI" },
  "miso soup": { gi: 10, confidence: 0.85, source: "IJGI" },
  "miso çorbası": { gi: 10, confidence: 0.85, source: "IJGI" },
  "edamame": { gi: 18, confidence: 0.88, source: "Sydney GI DB" },
  "onigiri": { gi: 70, confidence: 0.82, source: "IJGI" },
  "yakitori": { gi: 5, confidence: 0.82, source: "IJGI" },
  "teriyaki chicken": { gi: 10, confidence: 0.82, source: "IJGI" },
  "katsu curry": { gi: 60, confidence: 0.78, source: "IJGI" },
  "mochi": { gi: 78, confidence: 0.82, source: "IJGI" },
  "dorayaki": { gi: 65, confidence: 0.78, source: "IJGI" },
  "takoyaki": { gi: 55, confidence: 0.75, source: "IJGI" },

  // ── ÇİN MUTFAĞI ───────────────────────────────────────────────
  "chow mein": { gi: 57, confidence: 0.80, source: "IJGI" },
  "kung pao chicken": { gi: 35, confidence: 0.78, source: "IJGI" },
  "sweet and sour pork": { gi: 52, confidence: 0.78, source: "IJGI" },
  "wonton soup": { gi: 48, confidence: 0.78, source: "IJGI" },
  "peking duck": { gi: 15, confidence: 0.80, source: "IJGI" },
  "mapo tofu": { gi: 20, confidence: 0.78, source: "IJGI" },
  "congee": { gi: 78, confidence: 0.82, source: "Sydney GI DB" },

  // ── HİNT MUTFAĞI ──────────────────────────────────────────────
  "biryani": { gi: 58, confidence: 0.82, source: "IJGI" },
  "dal": { gi: 29, confidence: 0.90, source: "Sydney GI DB" },
  "samosa": { gi: 55, confidence: 0.78, source: "IJGI" },
  "butter chicken": { gi: 20, confidence: 0.80, source: "IJGI" },
  "chicken tikka masala": { gi: 20, confidence: 0.80, source: "IJGI" },
  "palak paneer": { gi: 15, confidence: 0.80, source: "IJGI" },
  "aloo gobi": { gi: 45, confidence: 0.78, source: "IJGI" },
  "idli": { gi: 70, confidence: 0.82, source: "IJGI" },
  "dosa": { gi: 69, confidence: 0.82, source: "IJGI" },
  "poha": { gi: 76, confidence: 0.80, source: "IJGI" },
  "halwa": { gi: 65, confidence: 0.78, source: "IJGI" },
  "kheer": { gi: 55, confidence: 0.78, source: "IJGI" },
  "lassi": { gi: 32, confidence: 0.80, source: "IJGI" },

  // ── ORTA DOĞU MUTFAĞI ─────────────────────────────────────────
  "falafel": { gi: 32, confidence: 0.85, source: "Sydney GI DB" },
  "shawarma": { gi: 38, confidence: 0.80, source: "IJGI" },
  "tabbouleh": { gi: 40, confidence: 0.82, source: "IJGI" },
  "fattoush": { gi: 40, confidence: 0.78, source: "IJGI" },
  "kibbeh": { gi: 42, confidence: 0.78, source: "IJGI" },
  "baba ganoush": { gi: 15, confidence: 0.85, source: "IJGI" },
  "pita": { gi: 57, confidence: 0.88, source: "Sydney GI DB" },
  "kushari": { gi: 55, confidence: 0.78, source: "IJGI" },
  "mansaf": { gi: 55, confidence: 0.75, source: "IJGI" },
  "muhallebi": { gi: 50, confidence: 0.75, source: "IJGI" },

  // ── MEKSİKA MUTFAĞI ───────────────────────────────────────────
  "taco": { gi: 52, confidence: 0.82, source: "IJGI" },
  "burrito": { gi: 55, confidence: 0.82, source: "IJGI" },
  "quesadilla": { gi: 52, confidence: 0.80, source: "IJGI" },
  "nachos": { gi: 58, confidence: 0.80, source: "IJGI" },
  "guacamole": { gi: 5, confidence: 0.92, source: "Sydney GI DB" },
  "salsa": { gi: 10, confidence: 0.88, source: "Sydney GI DB" },
  "enchilada": { gi: 52, confidence: 0.78, source: "IJGI" },
  "tamale": { gi: 60, confidence: 0.78, source: "IJGI" },
  "refried beans": { gi: 30, confidence: 0.82, source: "IJGI" },
  "churro": { gi: 68, confidence: 0.78, source: "IJGI" },

  // ── AMERİKAN / FAST FOOD ──────────────────────────────────────
  "hamburger": { gi: 61, confidence: 0.88, source: "Sydney GI DB" },
  "cheeseburger": { gi: 61, confidence: 0.85, source: "Sydney GI DB" },
  "hot dog": { gi: 52, confidence: 0.82, source: "IJGI" },
  "french fries": { gi: 63, confidence: 0.92, source: "Sydney GI DB" },
  "onion rings": { gi: 65, confidence: 0.80, source: "IJGI" },
  "fried chicken": { gi: 45, confidence: 0.82, source: "IJGI" },
  "chicken nuggets": { gi: 46, confidence: 0.82, source: "IJGI" },
  "fish and chips": { gi: 54, confidence: 0.82, source: "IJGI" },
  "macaroni and cheese": { gi: 64, confidence: 0.82, source: "IJGI" },
  "bbq ribs": { gi: 30, confidence: 0.80, source: "IJGI" },
  "coleslaw": { gi: 20, confidence: 0.80, source: "IJGI" },
  "donut": { gi: 76, confidence: 0.85, source: "Sydney GI DB" },
  "brownie": { gi: 43, confidence: 0.82, source: "Sydney GI DB" },
  "cheesecake": { gi: 35, confidence: 0.82, source: "Sydney GI DB" },
  "pancake syrup": { gi: 68, confidence: 0.82, source: "IJGI" },
  "hot dog bun": { gi: 73, confidence: 0.82, source: "IJGI" },

  // ── AKDENIZ MUTFAĞI ───────────────────────────────────────────
  "greek salad": { gi: 15, confidence: 0.85, source: "IJGI" },
  "greek yogurt": { gi: 11, confidence: 0.92, source: "Sydney GI DB" },
  "yunan yoğurdu": { gi: 11, confidence: 0.92, source: "Sydney GI DB" },
  "moussaka": { gi: 40, confidence: 0.78, source: "IJGI" },
  "spanakopita": { gi: 48, confidence: 0.78, source: "IJGI" },
  "paella": { gi: 67, confidence: 0.80, source: "IJGI" },
  "gazpacho": { gi: 15, confidence: 0.82, source: "IJGI" },
  "tapas": { gi: 25, confidence: 0.70, source: "IJGI" },
  "feta cheese": { gi: 0, confidence: 0.99, source: "Genel" },
  "olives": { gi: 0, confidence: 0.99, source: "Genel" },
  "zeytin": { gi: 0, confidence: 0.99, source: "Genel" },

  // ── KAHVALTI YİYECEKLERİ ──────────────────────────────────────
  "yumurta": { gi: 0, confidence: 0.99, source: "Genel" },
  "scrambled eggs": { gi: 0, confidence: 0.99, source: "Genel" },
  "omelet": { gi: 0, confidence: 0.99, source: "Genel" },
  "omlet": { gi: 0, confidence: 0.99, source: "Genel" },
  "sahanda yumurta": { gi: 0, confidence: 0.99, source: "Genel" },
  "haşlanmış yumurta": { gi: 0, confidence: 0.99, source: "Genel" },
  "bacon": { gi: 0, confidence: 0.99, source: "Genel" },
  "sausage": { gi: 28, confidence: 0.85, source: "Sydney GI DB" },
  "sucuk": { gi: 28, confidence: 0.85, source: "TürKomp" },
  "pastırma": { gi: 0, confidence: 0.95, source: "TürKomp" },
  "peynir": { gi: 0, confidence: 0.99, source: "Genel" },
  "beyaz peynir": { gi: 0, confidence: 0.99, source: "Genel" },
  "kaşar peyniri": { gi: 0, confidence: 0.99, source: "Genel" },
  "bal": { gi: 61, confidence: 0.95, source: "Sydney GI DB" },
  "honey": { gi: 61, confidence: 0.95, source: "Sydney GI DB" },
  "reçel": { gi: 65, confidence: 0.85, source: "TürKomp" },
  "jam": { gi: 65, confidence: 0.85, source: "Sydney GI DB" },
  "fıstık ezmesi": { gi: 14, confidence: 0.90, source: "Sydney GI DB" },
  "peanut butter": { gi: 14, confidence: 0.90, source: "Sydney GI DB" },
  "nutella": { gi: 55, confidence: 0.85, source: "IJGI" },

  // ── ET & BALIK ────────────────────────────────────────────────
  "biftek": { gi: 0, confidence: 0.99, source: "Genel" },
  "steak": { gi: 0, confidence: 0.99, source: "Genel" },
  "kuzu": { gi: 0, confidence: 0.99, source: "Genel" },
  "sığır": { gi: 0, confidence: 0.99, source: "Genel" },
  "tavuk": { gi: 0, confidence: 0.99, source: "Genel" },
  "hindi": { gi: 0, confidence: 0.99, source: "Genel" },
  "balık": { gi: 0, confidence: 0.99, source: "Genel" },
  "somon": { gi: 0, confidence: 0.99, source: "Genel" },
  "ton balığı": { gi: 0, confidence: 0.99, source: "Genel" },
  "karides": { gi: 0, confidence: 0.99, source: "Genel" },
  "ahtapot": { gi: 0, confidence: 0.99, source: "Genel" },
  "midye": { gi: 0, confidence: 0.99, source: "Genel" },
  "hamsi": { gi: 0, confidence: 0.99, source: "Genel" },
  "levrek": { gi: 0, confidence: 0.99, source: "Genel" },
  "çipura": { gi: 0, confidence: 0.99, source: "Genel" },
  "tuna": { gi: 0, confidence: 0.99, source: "Genel" },
  "salmon": { gi: 0, confidence: 0.99, source: "Genel" },
  "shrimp": { gi: 0, confidence: 0.99, source: "Genel" },

  // ── SEBZELERİ ─────────────────────────────────────────────────
  "patates": { gi: 78, confidence: 0.95, source: "Sydney GI DB" },
  "tatlı patates": { gi: 61, confidence: 0.92, source: "Sydney GI DB" },
  "sweet potato": { gi: 61, confidence: 0.92, source: "Sydney GI DB" },
  "havuç": { gi: 39, confidence: 0.90, source: "Sydney GI DB" },
  "bezelye": { gi: 51, confidence: 0.88, source: "Sydney GI DB" },
  "mısır": { gi: 52, confidence: 0.92, source: "Sydney GI DB" },
  "corn": { gi: 52, confidence: 0.92, source: "Sydney GI DB" },
  "kabak": { gi: 75, confidence: 0.88, source: "Sydney GI DB" },
  "balkabağı": { gi: 75, confidence: 0.88, source: "Sydney GI DB" },
  "pumpkin": { gi: 75, confidence: 0.88, source: "Sydney GI DB" },
  "beet": { gi: 64, confidence: 0.88, source: "Sydney GI DB" },
  "pancar": { gi: 64, confidence: 0.88, source: "Sydney GI DB" },
  "brokoli": { gi: 10, confidence: 0.95, source: "Genel" },
  "broccoli": { gi: 10, confidence: 0.95, source: "Genel" },
  "karnabahar": { gi: 10, confidence: 0.95, source: "Genel" },
  "ıspanak": { gi: 15, confidence: 0.95, source: "Genel" },
  "marul": { gi: 10, confidence: 0.95, source: "Genel" },
  "domates": { gi: 15, confidence: 0.95, source: "Genel" },
  "salatalık": { gi: 10, confidence: 0.95, source: "Genel" },
  "patlıcan": { gi: 15, confidence: 0.92, source: "Genel" },
  "biber": { gi: 10, confidence: 0.95, source: "Genel" },
  "soğan": { gi: 10, confidence: 0.95, source: "Genel" },
  "sarımsak": { gi: 10, confidence: 0.95, source: "Genel" },
  "mantar": { gi: 10, confidence: 0.95, source: "Genel" },
  "enginar": { gi: 15, confidence: 0.88, source: "Genel" },
  "kereviz": { gi: 10, confidence: 0.88, source: "Genel" },
  "kuşkonmaz": { gi: 15, confidence: 0.90, source: "Genel" },
  "asparagus": { gi: 15, confidence: 0.90, source: "Genel" },
  "avokado": { gi: 10, confidence: 0.95, source: "Sydney GI DB" },
  "avocado": { gi: 10, confidence: 0.95, source: "Sydney GI DB" },

  // ── MEYVELER ──────────────────────────────────────────────────
  "karpuz": { gi: 76, confidence: 0.88, source: "Sydney GI DB" },
  "kavun": { gi: 65, confidence: 0.85, source: "Sydney GI DB" },
  "muz": { gi: 51, confidence: 0.95, source: "Sydney GI DB" },
  "elma": { gi: 36, confidence: 0.95, source: "Sydney GI DB" },
  "armut": { gi: 38, confidence: 0.92, source: "Sydney GI DB" },
  "portakal": { gi: 43, confidence: 0.95, source: "Sydney GI DB" },
  "orange": { gi: 43, confidence: 0.95, source: "Sydney GI DB" },
  "mandalina": { gi: 42, confidence: 0.90, source: "Sydney GI DB" },
  "üzüm": { gi: 59, confidence: 0.92, source: "Sydney GI DB" },
  "çilek": { gi: 40, confidence: 0.92, source: "Sydney GI DB" },
  "strawberry": { gi: 40, confidence: 0.92, source: "Sydney GI DB" },
  "kiraz": { gi: 22, confidence: 0.88, source: "Sydney GI DB" },
  "cherry": { gi: 22, confidence: 0.88, source: "Sydney GI DB" },
  "şeftali": { gi: 43, confidence: 0.88, source: "Sydney GI DB" },
  "kayısı": { gi: 57, confidence: 0.85, source: "Sydney GI DB" },
  "erik": { gi: 40, confidence: 0.85, source: "Sydney GI DB" },
  "ananas": { gi: 66, confidence: 0.88, source: "Sydney GI DB" },
  "pineapple": { gi: 66, confidence: 0.88, source: "Sydney GI DB" },
  "mango": { gi: 51, confidence: 0.90, source: "Sydney GI DB" },
  "papaya": { gi: 60, confidence: 0.85, source: "Sydney GI DB" },
  "kivi": { gi: 53, confidence: 0.88, source: "Sydney GI DB" },
  "kiwi": { gi: 53, confidence: 0.88, source: "Sydney GI DB" },
  "nar": { gi: 35, confidence: 0.85, source: "Sydney GI DB" },
  "incir": { gi: 61, confidence: 0.85, source: "Sydney GI DB" },
  "hurma": { gi: 42, confidence: 0.88, source: "Sydney GI DB" },
  "dates": { gi: 42, confidence: 0.88, source: "Sydney GI DB" },
  "kuru üzüm": { gi: 64, confidence: 0.88, source: "Sydney GI DB" },
  "raisin": { gi: 64, confidence: 0.88, source: "Sydney GI DB" },
  "kuru kayısı": { gi: 31, confidence: 0.85, source: "Sydney GI DB" },
  "greyfurt": { gi: 25, confidence: 0.88, source: "Sydney GI DB" },
  "grapefruit": { gi: 25, confidence: 0.88, source: "Sydney GI DB" },

  // ── SÜT & SÜTLÜ ÜRÜNLER ───────────────────────────────────────
  "süt": { gi: 31, confidence: 0.95, source: "Sydney GI DB" },
  "yağlı süt": { gi: 27, confidence: 0.95, source: "Sydney GI DB" },
  "yağsız süt": { gi: 32, confidence: 0.95, source: "Sydney GI DB" },
  "full fat milk": { gi: 27, confidence: 0.95, source: "Sydney GI DB" },
  "skim milk": { gi: 32, confidence: 0.95, source: "Sydney GI DB" },
  "dondurma": { gi: 51, confidence: 0.90, source: "Sydney GI DB" },
  "ice cream": { gi: 51, confidence: 0.90, source: "Sydney GI DB" },
  "pudding": { gi: 44, confidence: 0.85, source: "Sydney GI DB" },
  "cream cheese": { gi: 0, confidence: 0.99, source: "Genel" },
  "sour cream": { gi: 0, confidence: 0.99, source: "Genel" },
  "butter": { gi: 0, confidence: 0.99, source: "Genel" },
  "tereyağı": { gi: 0, confidence: 0.99, source: "Genel" },

  // ── KURUYEMIŞLER & TOHUMLAR ────────────────────────────────────
  "badem": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "almond": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "ceviz": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "walnut": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "fıstık": { gi: 14, confidence: 0.92, source: "Sydney GI DB" },
  "peanut": { gi: 14, confidence: 0.92, source: "Sydney GI DB" },
  "antep fıstığı": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "pistachio": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "kaju": { gi: 25, confidence: 0.88, source: "Sydney GI DB" },
  "cashew": { gi: 25, confidence: 0.88, source: "Sydney GI DB" },
  "findik": { gi: 15, confidence: 0.88, source: "Sydney GI DB" },
  "hazelnut": { gi: 15, confidence: 0.88, source: "Sydney GI DB" },
  "chia seeds": { gi: 1, confidence: 0.90, source: "Sydney GI DB" },
  "chia tohumu": { gi: 1, confidence: 0.90, source: "Sydney GI DB" },
  "keten tohumu": { gi: 1, confidence: 0.90, source: "Sydney GI DB" },
  "flaxseed": { gi: 1, confidence: 0.90, source: "Sydney GI DB" },
  "susam": { gi: 10, confidence: 0.85, source: "Sydney GI DB" },
  "tahini": { gi: 10, confidence: 0.88, source: "Sydney GI DB" },

  // ── ATIŞTIRLLIKLAR & CIPSLER ──────────────────────────────────
  "cips": { gi: 57, confidence: 0.90, source: "Sydney GI DB" },
  "potato chips": { gi: 57, confidence: 0.90, source: "Sydney GI DB" },
  "corn chips": { gi: 63, confidence: 0.88, source: "Sydney GI DB" },
  "popcorn": { gi: 65, confidence: 0.88, source: "Sydney GI DB" },
  "mısır patlaği": { gi: 65, confidence: 0.88, source: "Sydney GI DB" },
  "rice cake": { gi: 82, confidence: 0.90, source: "Sydney GI DB" },
  "pirinç keki": { gi: 82, confidence: 0.90, source: "Sydney GI DB" },
  "cracker": { gi: 67, confidence: 0.85, source: "Sydney GI DB" },
  "bisküvi": { gi: 70, confidence: 0.85, source: "TürKomp" },
  "gofret": { gi: 66, confidence: 0.80, source: "TürKomp" },
  "çikolata": { gi: 40, confidence: 0.88, source: "Sydney GI DB" },
  "dark chocolate": { gi: 23, confidence: 0.90, source: "Sydney GI DB" },
  "bitter çikolata": { gi: 23, confidence: 0.90, source: "Sydney GI DB" },
  "milk chocolate": { gi: 43, confidence: 0.88, source: "Sydney GI DB" },
  "sütlü çikolata": { gi: 43, confidence: 0.88, source: "Sydney GI DB" },
  "candy bar": { gi: 55, confidence: 0.85, source: "IJGI" },
  "gummy bears": { gi: 94, confidence: 0.85, source: "Sydney GI DB" },
  "jelly beans": { gi: 80, confidence: 0.85, source: "Sydney GI DB" },
  "şeker": { gi: 65, confidence: 0.92, source: "Sydney GI DB" },
  "sugar": { gi: 65, confidence: 0.92, source: "Sydney GI DB" },

  // ── PASTANE & TATLILLAR ───────────────────────────────────────
  "kek": { gi: 54, confidence: 0.85, source: "Sydney GI DB" },
  "cake": { gi: 54, confidence: 0.85, source: "Sydney GI DB" },
  "cupcake": { gi: 65, confidence: 0.80, source: "IJGI" },
  "profiterol": { gi: 50, confidence: 0.78, source: "IJGI" },
  "milföy": { gi: 59, confidence: 0.78, source: "IJGI" },
  "éclair": { gi: 52, confidence: 0.78, source: "IJGI" },
  "macaroon": { gi: 55, confidence: 0.78, source: "IJGI" },
  "sorbet": { gi: 52, confidence: 0.82, source: "IJGI" },
  "panna cotta": { gi: 38, confidence: 0.78, source: "IJGI" },
  "creme brulee": { gi: 38, confidence: 0.78, source: "IJGI" },
  "mousse": { gi: 35, confidence: 0.78, source: "IJGI" },

  // ── İÇECEKLER ────────────────────────────────────────────────
  "su": { gi: 0, confidence: 0.99, source: "Genel" },
  "water": { gi: 0, confidence: 0.99, source: "Genel" },
  "kahve": { gi: 0, confidence: 0.99, source: "Genel" },
  "coffee": { gi: 0, confidence: 0.99, source: "Genel" },
  "espresso": { gi: 0, confidence: 0.99, source: "Genel" },
  "latte": { gi: 10, confidence: 0.90, source: "IJGI" },
  "cappuccino": { gi: 8, confidence: 0.90, source: "IJGI" },
  "portakal suyu": { gi: 50, confidence: 0.92, source: "Sydney GI DB" },
  "orange juice": { gi: 50, confidence: 0.92, source: "Sydney GI DB" },
  "elma suyu": { gi: 40, confidence: 0.88, source: "Sydney GI DB" },
  "apple juice": { gi: 40, confidence: 0.88, source: "Sydney GI DB" },
  "üzüm suyu": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "kola": { gi: 63, confidence: 0.92, source: "Sydney GI DB" },
  "cola": { gi: 63, confidence: 0.92, source: "Sydney GI DB" },
  "soda": { gi: 65, confidence: 0.88, source: "Sydney GI DB" },
  "enerji içeceği": { gi: 73, confidence: 0.85, source: "IJGI" },
  "energy drink": { gi: 73, confidence: 0.85, source: "IJGI" },
  "smoothie": { gi: 48, confidence: 0.78, source: "IJGI" },
  "soya sütü": { gi: 34, confidence: 0.88, source: "Sydney GI DB" },
  "soy milk": { gi: 34, confidence: 0.88, source: "Sydney GI DB" },
  "badem sütü": { gi: 25, confidence: 0.85, source: "IJGI" },
  "almond milk": { gi: 25, confidence: 0.85, source: "IJGI" },
  "bira": { gi: 66, confidence: 0.85, source: "Sydney GI DB" },
  "beer": { gi: 66, confidence: 0.85, source: "Sydney GI DB" },
  "şarap": { gi: 15, confidence: 0.85, source: "Sydney GI DB" },
  "wine": { gi: 15, confidence: 0.85, source: "Sydney GI DB" },

  // ── SOS & BAHARATLAR ──────────────────────────────────────────
  "ketçap": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "ketchup": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "mayonez": { gi: 0, confidence: 0.95, source: "Genel" },
  "mayonnaise": { gi: 0, confidence: 0.95, source: "Genel" },
  "hardal": { gi: 0, confidence: 0.99, source: "Genel" },
  "mustard": { gi: 0, confidence: 0.99, source: "Genel" },
  "soya sosu": { gi: 20, confidence: 0.85, source: "IJGI" },
  "soy sauce": { gi: 20, confidence: 0.85, source: "IJGI" },
  "sirke": { gi: 0, confidence: 0.99, source: "Genel" },
  "vinegar": { gi: 0, confidence: 0.99, source: "Genel" },
  "zeytinyağı": { gi: 0, confidence: 0.99, source: "Genel" },
  "olive oil": { gi: 0, confidence: 0.99, source: "Genel" },
};

export function lookupGI(name: string): GIEntry | null {
  const lower = name.toLowerCase().trim();
  if (GI_DATABASE[lower]) return GI_DATABASE[lower];
  for (const [key, val] of Object.entries(GI_DATABASE)) {
    if (lower.includes(key) || key.includes(lower)) return val;
  }
  return null;
}
