export const LANGUAGES = {
  en: "English", tr: "Türkçe", zh: "中文", hi: "हिन्दी",
  es: "Español", fr: "Français", ar: "العربية",
  pt: "Português", ru: "Русский", de: "Deutsch",
} as const;
export type Lang = keyof typeof LANGUAGES;
export const t: Record<Lang, Record<string, string>> = {
  en: { badge:"World's first AI glucose tracking app", upload:"Upload meal photo", drop:"or drag & drop", context_placeholder:"Add context (optional): breakfast, less oil...", analyze_btn:"🔬 Analyze Sugar & Glucose", analyzing:"⏳ Analyzing...", low_risk:"Low Risk", medium_risk:"Medium Risk", high_risk:"High Risk", gl_low:"✓ Minimal impact on blood sugar (GL < 10)", gl_medium:"⚠ Moderate impact on blood sugar (GL 10-20)", gl_high:"⛔ Significant blood sugar spike (GL > 20)", total_sugar:"Total Sugar", net_carbs:"Net Carbs", fiber:"Fiber", glucose_response:"Glucose Response", detected_foods:"Detected Foods", tips:"💡 Tips", disclaimer:"This analysis is not medical advice.", error_image:"Only image files accepted", error_size:"Image must be under 5MB", error_failed:"Analysis failed", peak:"📈", pre_meal_tip:"Take a photo before eating to predict glucose impact.", compare_tip:"Upload two meals to compare GL side by side.", no_food:"No food detected. Please take a photo of a meal or drink.", offline_msg:"Offline — Analysis requires internet. Your history is still available.", save_success:"Saved to history", search_placeholder:"Search any food...", ai_analyzing:"AI analyzing" },
  tr: { badge:"Dünyanın ilk AI glukoz takip uygulaması", upload:"Yemek fotoğrafı yükle", drop:"veya sürükle bırak", context_placeholder:"Ek bilgi (isteğe bağlı): kahvaltı, az yağlı...", analyze_btn:"🔬 Şeker & Glukoz Analiz Et", analyzing:"⏳ Analiz ediliyor...", low_risk:"Düşük Risk", medium_risk:"Orta Risk", high_risk:"Yüksek Risk", gl_low:"✓ Kan şekerini çok az etkiler (GL < 10)", gl_medium:"⚠ Kan şekerini orta düzeyde etkiler (GL 10-20)", gl_high:"⛔ Kan şekerini önemli ölçüde yükseltir (GL > 20)", total_sugar:"Toplam Şeker", net_carbs:"Net Karbonhidrat", fiber:"Lif", glucose_response:"Glukoz Yanıtı", detected_foods:"Tespit Edilen Yiyecekler", tips:"💡 Öneriler", disclaimer:"Bu analiz tıbbi tavsiye değildir.", error_image:"Sadece görsel kabul edilir", error_size:"Görsel 5MB altında olmalı", error_failed:"Analiz başarısız", peak:"📈", pre_meal_tip:"Yemekten önce fotoğraf çekerek glukoz etkisini tahmin edin.", compare_tip:"İki yemeği karşılaştırmak için fotoğraf yükleyin.", no_food:"Yiyecek tespit edilemedi. Lütfen yemek veya içecek fotoğrafı çekin.", offline_msg:"Çevrimdışı — Analiz için internet gerekli. Geçmişinize erişebilirsiniz.", save_success:"Geçmişe kaydedildi", search_placeholder:"Herhangi bir yiyecek ara...", ai_analyzing:"AI analiz ediyor" },
  zh: { badge:"全球首款AI血糖追踪应用", upload:"上传餐食照片", drop:"或拖放至此", context_placeholder:"补充信息（可选）", analyze_btn:"🔬 分析糖分和血糖", analyzing:"⏳ 分析中...", low_risk:"低风险", medium_risk:"中风险", high_risk:"高风险", gl_low:"✓ 对血糖影响极小 (GL < 10)", gl_medium:"⚠ 对血糖影响适中 (GL 10-20)", gl_high:"⛔ 血糖显著升高 (GL > 20)", total_sugar:"总糖量", net_carbs:"净碳水", fiber:"膳食纤维", glucose_response:"血糖反应", detected_foods:"检测到的食物", tips:"💡 建议", disclaimer:"此分析不构成医疗建议。", error_image:"仅接受图片文件", error_size:"图片必须小于5MB", error_failed:"分析失败", peak:"📈", pre_meal_tip:"餐前拍照预测血糖影响。", compare_tip:"上传两餐进行GL对比。", no_food:"未检测到食物，请拍摄餐食或饮品照片。", offline_msg:"离线 — 分析需要网络。历史记录仍可访问。", save_success:"已保存到历史", search_placeholder:"搜索任何食物...", ai_analyzing:"AI分析中" },
  hi: { badge:"विश्व का पहला AI ग्लूकोज ट्रैकिंग ऐप", upload:"भोजन की फोटो अपलोड करें", drop:"या खींचें और छोड़ें", context_placeholder:"अतिरिक्त जानकारी (वैकल्पिक)", analyze_btn:"🔬 शुगर और ग्लूकोज विश्लेषण करें", analyzing:"⏳ विश्लेषण हो रहा है...", low_risk:"कम जोखिम", medium_risk:"मध्यम जोखिम", high_risk:"उच्च जोखिम", gl_low:"✓ रक्त शर्करा पर न्यूनतम प्रभाव", gl_medium:"⚠ रक्त शर्करा पर मध्यम प्रभाव", gl_high:"⛔ रक्त शर्करा में वृद्धि", total_sugar:"कुल शुगर", net_carbs:"नेट कार्ब्स", fiber:"फाइबर", glucose_response:"ग्लूकोज प्रतिक्रिया", detected_foods:"पहचाने गए खाद्य पदार्थ", tips:"💡 सुझाव", disclaimer:"यह विश्लेषण चिकित्सीय सलाह नहीं है।", error_image:"केवल छवि फ़ाइलें", error_size:"छवि 5MB से कम", error_failed:"विश्लेषण विफल", peak:"📈", pre_meal_tip:"खाने से पहले फोटो लें।", compare_tip:"दो भोजन की तुलना करें।", no_food:"कोई खाना नहीं मिला। भोजन की फोटो लें।", offline_msg:"ऑफलाइन — विश्लेषण के लिए इंटरनेट चाहिए।", save_success:"इतिहास में सहेजा", search_placeholder:"कोई भी खाना खोजें...", ai_analyzing:"AI विश्लेषण" },
  es: { badge:"La primera app mundial de glucosa con IA", upload:"Subir foto de comida", drop:"o arrastra y suelta", context_placeholder:"Contexto adicional (opcional)", analyze_btn:"🔬 Analizar Azúcar y Glucosa", analyzing:"⏳ Analizando...", low_risk:"Riesgo Bajo", medium_risk:"Riesgo Medio", high_risk:"Riesgo Alto", gl_low:"✓ Impacto mínimo en azúcar (GL < 10)", gl_medium:"⚠ Impacto moderado en azúcar (GL 10-20)", gl_high:"⛔ Pico significativo de azúcar (GL > 20)", total_sugar:"Azúcar Total", net_carbs:"Carbohidratos Netos", fiber:"Fibra", glucose_response:"Respuesta de Glucosa", detected_foods:"Alimentos Detectados", tips:"💡 Consejos", disclaimer:"Este análisis no es consejo médico.", error_image:"Solo archivos de imagen", error_size:"La imagen debe ser menor de 5MB", error_failed:"Análisis fallido", peak:"📈", pre_meal_tip:"Toma una foto antes de comer.", compare_tip:"Sube dos comidas para comparar GL.", no_food:"No se detectó comida. Toma una foto de una comida.", offline_msg:"Sin conexión — Se necesita internet para el análisis.", save_success:"Guardado en historial", search_placeholder:"Buscar cualquier alimento...", ai_analyzing:"IA analizando" },
  fr: { badge:"La première app mondiale de suivi du glucose par IA", upload:"Télécharger une photo de repas", drop:"ou glisser-déposer", context_placeholder:"Contexte supplémentaire (optionnel)", analyze_btn:"🔬 Analyser Sucre & Glucose", analyzing:"⏳ Analyse en cours...", low_risk:"Risque Faible", medium_risk:"Risque Modéré", high_risk:"Risque Élevé", gl_low:"✓ Impact minimal sur la glycémie (GL < 10)", gl_medium:"⚠ Impact modéré sur la glycémie (GL 10-20)", gl_high:"⛔ Pic glycémique significatif (GL > 20)", total_sugar:"Sucre Total", net_carbs:"Glucides Nets", fiber:"Fibres", glucose_response:"Réponse Glycémique", detected_foods:"Aliments Détectés", tips:"💡 Conseils", disclaimer:"Cette analyse n'est pas un avis médical.", error_image:"Seuls les fichiers image", error_size:"L'image doit être inférieure à 5 Mo", error_failed:"Analyse échouée", peak:"📈", pre_meal_tip:"Prenez une photo avant de manger.", compare_tip:"Téléchargez deux repas pour comparer.", no_food:"Aucun aliment détecté. Prenez une photo d'un repas.", offline_msg:"Hors ligne — Internet requis pour l'analyse.", save_success:"Enregistré dans l'historique", search_placeholder:"Rechercher un aliment...", ai_analyzing:"IA en analyse" },
  ar: { badge:"أول تطبيق عالمي لتتبع الجلوكوز بالذكاء الاصطناعي", upload:"ارفع صورة الوجبة", drop:"أو اسحب وأفلت", context_placeholder:"معلومات إضافية (اختياري)", analyze_btn:"🔬 تحليل السكر والجلوكوز", analyzing:"⏳ جارٍ التحليل...", low_risk:"خطر منخفض", medium_risk:"خطر متوسط", high_risk:"خطر عالٍ", gl_low:"✓ تأثير ضئيل على سكر الدم (GL < 10)", gl_medium:"⚠ تأثير متوسط على سكر الدم (GL 10-20)", gl_high:"⛔ ارتفاع كبير في سكر الدم (GL > 20)", total_sugar:"السكر الكلي", net_carbs:"الكربوهيدرات الصافية", fiber:"الألياف", glucose_response:"استجابة الجلوكوز", detected_foods:"الأطعمة المكتشفة", tips:"💡 نصائح", disclaimer:"هذا التحليل ليس نصيحة طبية.", error_image:"يُقبل فقط ملفات الصور", error_size:"يجب أن تكون الصورة أقل من 5 ميجابايت", error_failed:"فشل التحليل", peak:"📈", pre_meal_tip:"التقط صورة قبل الأكل للتنبؤ بتأثير الجلوكوز.", compare_tip:"ارفع وجبتين لمقارنة GL.", no_food:"لم يتم اكتشاف طعام. يرجى التقاط صورة لوجبة أو مشروب.", offline_msg:"غير متصل — يتطلب التحليل إنترنت. سجلك لا يزال متاحاً.", save_success:"تم الحفظ في السجل", search_placeholder:"ابحث عن أي طعام...", ai_analyzing:"الذكاء الاصطناعي يحلل" },
  pt: { badge:"O primeiro app mundial de rastreamento de glicose com IA", upload:"Enviar foto da refeição", drop:"ou arraste e solte", context_placeholder:"Contexto adicional (opcional)", analyze_btn:"🔬 Analisar Açúcar & Glicose", analyzing:"⏳ Analisando...", low_risk:"Baixo Risco", medium_risk:"Risco Médio", high_risk:"Alto Risco", gl_low:"✓ Impacto mínimo no açúcar (GL < 10)", gl_medium:"⚠ Impacto moderado no açúcar (GL 10-20)", gl_high:"⛔ Pico significativo de açúcar (GL > 20)", total_sugar:"Açúcar Total", net_carbs:"Carboidratos Líquidos", fiber:"Fibra", glucose_response:"Resposta da Glicose", detected_foods:"Alimentos Detectados", tips:"💡 Dicas", disclaimer:"Esta análise não é conselho médico.", error_image:"Apenas arquivos de imagem", error_size:"A imagem deve ter menos de 5MB", error_failed:"Análise falhou", peak:"📈", pre_meal_tip:"Tire uma foto antes de comer para prever o impacto glicêmico.", compare_tip:"Envie duas refeições para comparar o GL.", no_food:"Nenhum alimento detectado. Tire uma foto de uma refeição.", offline_msg:"Offline — Análise requer internet. Seu histórico ainda está disponível.", save_success:"Salvo no histórico", search_placeholder:"Pesquisar qualquer alimento...", ai_analyzing:"IA analisando" },
  ru: { badge:"Первое в мире приложение для отслеживания глюкозы с ИИ", upload:"Загрузить фото блюда", drop:"или перетащите файл", context_placeholder:"Дополнительная информация (необязательно)", analyze_btn:"🔬 Анализ сахара и глюкозы", analyzing:"⏳ Анализируется...", low_risk:"Низкий риск", medium_risk:"Средний риск", high_risk:"Высокий риск", gl_low:"✓ Минимальное влияние на сахар (GL < 10)", gl_medium:"⚠ Умеренное влияние на сахар (GL 10-20)", gl_high:"⛔ Значительный скачок сахара (GL > 20)", total_sugar:"Всего сахара", net_carbs:"Чистые углеводы", fiber:"Клетчатка", glucose_response:"Гликемический ответ", detected_foods:"Обнаруженные продукты", tips:"💡 Советы", disclaimer:"Этот анализ не является медицинской консультацией.", error_image:"Только файлы изображений", error_size:"Изображение менее 5 МБ", error_failed:"Анализ не удался", peak:"📈", pre_meal_tip:"Сфотографируйте еду до еды для прогноза уровня глюкозы.", compare_tip:"Загрузите два блюда для сравнения GL.", no_food:"Еда не обнаружена. Пожалуйста, сфотографируйте блюдо или напиток.", offline_msg:"Офлайн — для анализа нужен интернет. История по-прежнему доступна.", save_success:"Сохранено в истории", search_placeholder:"Поиск любого продукта...", ai_analyzing:"ИИ анализирует" },
  de: { badge:"Die weltweit erste KI-Glukose-Tracking-App", upload:"Essensfoto hochladen", drop:"oder per Drag & Drop", context_placeholder:"Zusätzlicher Kontext (optional)", analyze_btn:"🔬 Zucker & Glukose analysieren", analyzing:"⏳ Wird analysiert...", low_risk:"Geringes Risiko", medium_risk:"Mittleres Risiko", high_risk:"Hohes Risiko", gl_low:"✓ Minimale Auswirkung auf Blutzucker (GL < 10)", gl_medium:"⚠ Moderate Auswirkung auf Blutzucker (GL 10-20)", gl_high:"⛔ Signifikanter Blutzuckeranstieg (GL > 20)", total_sugar:"Gesamtzucker", net_carbs:"Netto-Kohlenhydrate", fiber:"Ballaststoffe", glucose_response:"Glukoseantwort", detected_foods:"Erkannte Lebensmittel", tips:"💡 Tipps", disclaimer:"Diese Analyse ist kein medizinischer Rat.", error_image:"Nur Bilddateien", error_size:"Bild muss kleiner als 5 MB sein", error_failed:"Analyse fehlgeschlagen", peak:"📈", pre_meal_tip:"Mach ein Foto vor dem Essen, um die Glukosewirkung vorherzusagen.", compare_tip:"Lade zwei Mahlzeiten hoch, um GL zu vergleichen.", no_food:"Kein Essen erkannt. Bitte mach ein Foto von einer Mahlzeit.", offline_msg:"Offline — Analyse erfordert Internet. Dein Verlauf ist noch verfügbar.", save_success:"Im Verlauf gespeichert", search_placeholder:"Beliebiges Lebensmittel suchen...", ai_analyzing:"KI analysiert" },
};

// ── Expanded translations (key-first for maintainability) ───────────────────
// Each entry lists all 10 languages together so completeness is verifiable at a
// glance. Merged into `t` at load; always access via getT(lang) for EN fallback.
const ADDITIONS: Record<string, Record<Lang, string>> = {
  // Onboarding / profile setup
  pt_healthy: { en:"Healthy", tr:"Sağlıklı", zh:"健康", hi:"स्वस्थ", es:"Saludable", fr:"En bonne santé", ar:"صحي", pt:"Saudável", ru:"Здоров", de:"Gesund" },
  pt_healthy_desc: { en:"General wellness & sugar awareness", tr:"Genel sağlık ve şeker farkındalığı", zh:"整体健康与血糖意识", hi:"सामान्य स्वास्थ्य और शुगर जागरूकता", es:"Bienestar general y conciencia del azúcar", fr:"Bien-être général et conscience du sucre", ar:"العافية العامة والوعي بالسكر", pt:"Bem-estar geral e consciência do açúcar", ru:"Общее здоровье и контроль сахара", de:"Allgemeines Wohlbefinden & Zuckerbewusstsein" },
  pt_pre: { en:"Pre-diabetic", tr:"Pre-diyabet", zh:"糖尿病前期", hi:"प्री-डायबिटिक", es:"Prediabético", fr:"Prédiabétique", ar:"ما قبل السكري", pt:"Pré-diabético", ru:"Преддиабет", de:"Prädiabetisch" },
  pt_pre_desc: { en:"Monitoring borderline blood sugar patterns", tr:"Sınırda kan şekeri seviyelerini izleme", zh:"监测临界血糖模式", hi:"सीमावर्ती रक्त शर्करा पैटर्न की निगरानी", es:"Monitoreo de patrones límite de azúcar en sangre", fr:"Suivi des taux de glycémie limites", ar:"مراقبة أنماط سكر الدم الحدية", pt:"Monitoramento de padrões limítrofes de açúcar no sangue", ru:"Контроль пограничного уровня сахара", de:"Überwachung grenzwertiger Blutzuckermuster" },
  pt_diabetic: { en:"Diabetic", tr:"Diyabet", zh:"糖尿病", hi:"मधुमेह", es:"Diabético", fr:"Diabétique", ar:"مصاب بالسكري", pt:"Diabético", ru:"Диабет", de:"Diabetiker" },
  pt_diabetic_desc: { en:"Glucose awareness support — consult your doctor", tr:"Glukoz farkındalık desteği — doktorunuza danışın", zh:"血糖意识支持 — 请咨询医生", hi:"ग्लूकोज जागरूकता सहायता — अपने डॉक्टर से सलाह लें", es:"Apoyo de conciencia de glucosa — consulte a su médico", fr:"Soutien à la conscience du glucose — consultez votre médecin", ar:"دعم الوعي بالجلوكوز — استشر طبيبك", pt:"Apoio à consciência da glicose — consulte seu médico", ru:"Поддержка контроля глюкозы — проконсультируйтесь с врачом", de:"Glukose-Bewusstsein — konsultieren Sie Ihren Arzt" },
  ob_welcome: { en:"Welcome to GlucoLens", tr:"GlucoLens'e Hoş Geldiniz", zh:"欢迎使用 GlucoLens", hi:"GlucoLens में आपका स्वागत है", es:"Bienvenido a GlucoLens", fr:"Bienvenue sur GlucoLens", ar:"مرحباً بك في GlucoLens", pt:"Bem-vindo ao GlucoLens", ru:"Добро пожаловать в GlucoLens", de:"Willkommen bei GlucoLens" },
  ob_welcome_sub: { en:"Let's personalize your glucose tracking experience.", tr:"Glukoz takip deneyiminizi kişiselleştirelim.", zh:"让我们个性化您的血糖追踪体验。", hi:"आइए आपके ग्लूकोज ट्रैकिंग अनुभव को वैयक्तिक बनाएं।", es:"Personalicemos tu experiencia de seguimiento de glucosa.", fr:"Personnalisons votre suivi du glucose.", ar:"لنخصّص تجربة تتبع الجلوكوز الخاصة بك.", pt:"Vamos personalizar sua experiência de monitoramento de glicose.", ru:"Давайте персонализируем отслеживание глюкозы.", de:"Personalisieren wir dein Glukose-Tracking." },
  ob_name_label: { en:"Your name (optional)", tr:"Adınız (isteğe bağlı)", zh:"您的名字（可选）", hi:"आपका नाम (वैकल्पिक)", es:"Tu nombre (opcional)", fr:"Votre nom (facultatif)", ar:"اسمك (اختياري)", pt:"Seu nome (opcional)", ru:"Ваше имя (необязательно)", de:"Dein Name (optional)" },
  ob_name_ph: { en:"e.g. Yasevi", tr:"örn. Yasevi", zh:"例如 Yasevi", hi:"उदा. Yasevi", es:"p. ej. Yasevi", fr:"p. ex. Yasevi", ar:"مثال: Yasevi", pt:"ex. Yasevi", ru:"напр. Yasevi", de:"z. B. Yasevi" },
  ob_continue: { en:"Continue →", tr:"Devam →", zh:"继续 →", hi:"जारी रखें →", es:"Continuar →", fr:"Continuer →", ar:"متابعة →", pt:"Continuar →", ru:"Продолжить →", de:"Weiter →" },
  ob_profile_title: { en:"Your health profile", tr:"Sağlık profiliniz", zh:"您的健康档案", hi:"आपकी स्वास्थ्य प्रोफ़ाइल", es:"Tu perfil de salud", fr:"Votre profil de santé", ar:"ملفك الصحي", pt:"Seu perfil de saúde", ru:"Ваш профиль здоровья", de:"Dein Gesundheitsprofil" },
  ob_profile_sub: { en:"This sets your daily GL targets and warning thresholds.", tr:"Bu, günlük GL hedeflerinizi ve uyarı eşiklerinizi belirler.", zh:"这将设置您的每日 GL 目标和警告阈值。", hi:"यह आपके दैनिक GL लक्ष्य और चेतावनी सीमाएँ निर्धारित करता है।", es:"Esto establece tus objetivos diarios de GL y umbrales de advertencia.", fr:"Cela définit vos objectifs GL quotidiens et seuils d'alerte.", ar:"يحدد هذا أهداف الحمل الجلوكوزي اليومية وعتبات التحذير.", pt:"Isso define suas metas diárias de GL e limites de alerta.", ru:"Это задаёт ваши дневные цели GL и пороги предупреждений.", de:"Dies legt deine täglichen GL-Ziele und Warnschwellen fest." },
  ob_daily_target: { en:"Daily target", tr:"Günlük hedef", zh:"每日目标", hi:"दैनिक लक्ष्य", es:"Objetivo diario", fr:"Objectif quotidien", ar:"الهدف اليومي", pt:"Meta diária", ru:"Дневная цель", de:"Tagesziel" },
  ob_your_daily_target: { en:"Your daily GL target:", tr:"Günlük GL hedefiniz:", zh:"您的每日 GL 目标：", hi:"आपका दैनिक GL लक्ष्य:", es:"Tu objetivo diario de GL:", fr:"Votre objectif GL quotidien :", ar:"هدف الحمل الجلوكوزي اليومي:", pt:"Sua meta diária de GL:", ru:"Ваша дневная цель GL:", de:"Dein tägliches GL-Ziel:" },
  ob_max_per_meal: { en:"Max per meal: GL", tr:"Öğün başına maks: GL", zh:"每餐上限：GL", hi:"प्रति भोजन अधिकतम: GL", es:"Máx por comida: GL", fr:"Max par repas : GL", ar:"الحد الأقصى للوجبة: GL", pt:"Máx por refeição: GL", ru:"Макс на приём: GL", de:"Max pro Mahlzeit: GL" },
  ob_disclaimer_important: { en:"Important:", tr:"Önemli:", zh:"重要：", hi:"महत्वपूर्ण:", es:"Importante:", fr:"Important :", ar:"هام:", pt:"Importante:", ru:"Важно:", de:"Wichtig:" },
  ob_disclaimer_body: { en:"GlucoLens provides AI-based estimates only. Results are not medical diagnoses or treatment recommendations. Always consult a qualified healthcare professional for medical decisions.", tr:"GlucoLens yalnızca yapay zeka tabanlı tahminler sunar. Sonuçlar tıbbi teşhis veya tedavi önerisi değildir. Tıbbi kararlar için her zaman nitelikli bir sağlık uzmanına danışın.", zh:"GlucoLens 仅提供基于 AI 的估算。结果不构成医疗诊断或治疗建议。医疗决策请务必咨询合格的医疗专业人员。", hi:"GlucoLens केवल AI-आधारित अनुमान प्रदान करता है। परिणाम चिकित्सा निदान या उपचार सिफारिशें नहीं हैं। चिकित्सा निर्णयों के लिए हमेशा योग्य स्वास्थ्य पेशेवर से सलाह लें।", es:"GlucoLens solo proporciona estimaciones basadas en IA. Los resultados no son diagnósticos médicos ni recomendaciones de tratamiento. Consulte siempre a un profesional de salud cualificado para decisiones médicas.", fr:"GlucoLens fournit uniquement des estimations basées sur l'IA. Les résultats ne sont ni des diagnostics médicaux ni des recommandations de traitement. Consultez toujours un professionnel de santé qualifié pour les décisions médicales.", ar:"يقدّم GlucoLens تقديرات قائمة على الذكاء الاصطناعي فقط. النتائج ليست تشخيصاً طبياً أو توصيات علاجية. استشر دائماً أخصائي رعاية صحية مؤهلاً للقرارات الطبية.", pt:"O GlucoLens fornece apenas estimativas baseadas em IA. Os resultados não são diagnósticos médicos nem recomendações de tratamento. Consulte sempre um profissional de saúde qualificado para decisões médicas.", ru:"GlucoLens предоставляет только оценки на основе ИИ. Результаты не являются медицинским диагнозом или рекомендациями по лечению. Для медицинских решений всегда консультируйтесь с квалифицированным врачом.", de:"GlucoLens liefert nur KI-basierte Schätzungen. Die Ergebnisse sind keine medizinischen Diagnosen oder Behandlungsempfehlungen. Konsultiere für medizinische Entscheidungen stets eine qualifizierte Fachkraft." },
  ob_disclaimer_agree: { en:"I understand GlucoLens is an estimation tool, not a medical device. I agree to the", tr:"GlucoLens'in tıbbi bir cihaz değil, bir tahmin aracı olduğunu anlıyorum. Şunları kabul ediyorum:", zh:"我理解 GlucoLens 是估算工具，而非医疗设备。我同意", hi:"मैं समझता हूँ कि GlucoLens एक अनुमान उपकरण है, चिकित्सा उपकरण नहीं। मैं सहमत हूँ", es:"Entiendo que GlucoLens es una herramienta de estimación, no un dispositivo médico. Acepto la", fr:"Je comprends que GlucoLens est un outil d'estimation, pas un dispositif médical. J'accepte la", ar:"أفهم أن GlucoLens أداة تقدير وليست جهازاً طبياً. أوافق على", pt:"Entendo que o GlucoLens é uma ferramenta de estimativa, não um dispositivo médico. Concordo com a", ru:"Я понимаю, что GlucoLens — инструмент оценки, а не медицинское устройство. Я принимаю", de:"Ich verstehe, dass GlucoLens ein Schätzwerkzeug ist, kein Medizinprodukt. Ich stimme der" },
  ob_privacy: { en:"Privacy Policy", tr:"Gizlilik Politikası", zh:"隐私政策", hi:"गोपनीयता नीति", es:"Política de Privacidad", fr:"Politique de confidentialité", ar:"سياسة الخصوصية", pt:"Política de Privacidade", ru:"Политике конфиденциальности", de:"Datenschutzrichtlinie" },
  ob_terms: { en:"Terms of Use", tr:"Kullanım Koşulları", zh:"使用条款", hi:"उपयोग की शर्तें", es:"Términos de Uso", fr:"Conditions d'utilisation", ar:"شروط الاستخدام", pt:"Termos de Uso", ru:"Условия использования", de:"Nutzungsbedingungen" },
  ob_and: { en:"and", tr:"ve", zh:"和", hi:"और", es:"y", fr:"et", ar:"و", pt:"e", ru:"и", de:"und" },
  ob_back: { en:"← Back", tr:"← Geri", zh:"← 返回", hi:"← वापस", es:"← Atrás", fr:"← Retour", ar:"← رجوع", pt:"← Voltar", ru:"← Назад", de:"← Zurück" },
  ob_start: { en:"Start Tracking", tr:"Takibe Başla", zh:"开始追踪", hi:"ट्रैकिंग शुरू करें", es:"Comenzar Seguimiento", fr:"Commencer le suivi", ar:"ابدأ التتبع", pt:"Começar Monitoramento", ru:"Начать отслеживание", de:"Tracking starten" },
};
for (const key of Object.keys(ADDITIONS)) {
  for (const lang of Object.keys(LANGUAGES) as Lang[]) {
    t[lang][key] = ADDITIONS[key][lang] ?? ADDITIONS[key].en;
  }
}
// Per-language accessor with graceful fallback. Returns the requested
// language's string; if a key is missing for that language it falls back to
// English, and finally to the key name itself — so a not-yet-translated string
// never renders as `undefined`/blank during the multi-language rollout.
export function getT(lang: Lang): Record<string, string> {
  const base = t[lang] ?? t.en;
  return new Proxy(base, {
    get(target, prop) {
      if (typeof prop !== "string") return undefined;
      return target[prop] ?? t.en[prop] ?? prop;
    },
  }) as Record<string, string>;
}

export function detectBrowserLang(): Lang {
  if (typeof navigator === "undefined") return "en";
  const lang = navigator.language.slice(0, 2).toLowerCase();
  return (lang in LANGUAGES ? lang : "en") as Lang;
}
