export const LANGUAGES = {
  en: "English", tr: "Türkçe", zh: "中文", hi: "हिन्दी",
  es: "Español", fr: "Français", ar: "العربية",
  pt: "Português", ru: "Русский", de: "Deutsch",
} as const;
export type Lang = keyof typeof LANGUAGES;
export const t: Record<Lang, Record<string, string>> = {
  en: { badge:"World's first AI glucose tracking app", upload:"Upload meal photo", drop:"or drag & drop", context_placeholder:"Add context (optional): breakfast, less oil...", analyze_btn:"🔬 Analyze Sugar & Glucose", analyzing:"⏳ Analyzing...", low_risk:"Low Risk", medium_risk:"Medium Risk", high_risk:"High Risk", gl_low:"✓ Minimal impact on blood sugar (GL < 10)", gl_medium:"⚠ Moderate impact on blood sugar (GL 10-20)", gl_high:"⛔ Significant blood sugar spike (GL > 20)", total_sugar:"Total Sugar", net_carbs:"Net Carbs", fiber:"Fiber", glucose_response:"Glucose Response", detected_foods:"Detected Foods", tips:"💡 Tips", disclaimer:"This analysis is not medical advice.", error_image:"Only image files accepted", error_size:"Image must be under 5MB", error_failed:"Analysis failed", peak:"📈" },
  tr: { badge:"Dünyanın ilk AI glukoz takip uygulaması", upload:"Yemek fotoğrafı yükle", drop:"veya sürükle bırak", context_placeholder:"Ek bilgi (isteğe bağlı): kahvaltı, az yağlı...", analyze_btn:"🔬 Şeker & Glukoz Analiz Et", analyzing:"⏳ Analiz ediliyor...", low_risk:"Düşük Risk", medium_risk:"Orta Risk", high_risk:"Yüksek Risk", gl_low:"✓ Kan şekerini çok az etkiler (GL < 10)", gl_medium:"⚠ Kan şekerini orta düzeyde etkiler (GL 10-20)", gl_high:"⛔ Kan şekerini önemli ölçüde yükseltir (GL > 20)", total_sugar:"Toplam Şeker", net_carbs:"Net Karbonhidrat", fiber:"Lif", glucose_response:"Glukoz Yanıtı", detected_foods:"Tespit Edilen Yiyecekler", tips:"💡 Öneriler", disclaimer:"Bu analiz tıbbi tavsiye değildir.", error_image:"Sadece görsel kabul edilir", error_size:"Görsel 5MB altında olmalı", error_failed:"Analiz başarısız", peak:"📈" },
  zh: { badge:"全球首款AI血糖追踪应用", upload:"上传餐食照片", drop:"或拖放至此", context_placeholder:"补充信息（可选）", analyze_btn:"🔬 分析糖分和血糖", analyzing:"⏳ 分析中...", low_risk:"低风险", medium_risk:"中风险", high_risk:"高风险", gl_low:"✓ 对血糖影响极小 (GL < 10)", gl_medium:"⚠ 对血糖影响适中 (GL 10-20)", gl_high:"⛔ 血糖显著升高 (GL > 20)", total_sugar:"总糖量", net_carbs:"净碳水", fiber:"膳食纤维", glucose_response:"血糖反应", detected_foods:"检测到的食物", tips:"💡 建议", disclaimer:"此分析不构成医疗建议。", error_image:"仅接受图片文件", error_size:"图片必须小于5MB", error_failed:"分析失败", peak:"📈" },
  hi: { badge:"विश्व का पहला AI ग्लूकोज ट्रैकिंग ऐप", upload:"भोजन की फोटो अपलोड करें", drop:"या खींचें और छोड़ें", context_placeholder:"अतिरिक्त जानकारी (वैकल्पिक)", analyze_btn:"🔬 शुगर और ग्लूकोज विश्लेषण करें", analyzing:"⏳ विश्लेषण हो रहा है...", low_risk:"कम जोखिम", medium_risk:"मध्यम जोखिम", high_risk:"उच्च जोखिम", gl_low:"✓ रक्त शर्करा पर न्यूनतम प्रभाव", gl_medium:"⚠ रक्त शर्करा पर मध्यम प्रभाव", gl_high:"⛔ रक्त शर्करा में वृद्धि", total_sugar:"कुल शुगर", net_carbs:"नेट कार्ब्स", fiber:"फाइबर", glucose_response:"ग्लूकोज प्रतिक्रिया", detected_foods:"पहचाने गए खाद्य पदार्थ", tips:"💡 सुझाव", disclaimer:"यह विश्लेषण चिकित्सीय सलाह नहीं है।", error_image:"केवल छवि फ़ाइलें", error_size:"छवि 5MB से कम", error_failed:"विश्लेषण विफल", peak:"📈" },
  es: { badge:"La primera app mundial de glucosa con IA", upload:"Subir foto de comida", drop:"o arrastra y suelta", context_placeholder:"Contexto adicional (opcional)", analyze_btn:"🔬 Analizar Azúcar y Glucosa", analyzing:"⏳ Analizando...", low_risk:"Riesgo Bajo", medium_risk:"Riesgo Medio", high_risk:"Riesgo Alto", gl_low:"✓ Impacto mínimo en azúcar (GL < 10)", gl_medium:"⚠ Impacto moderado en azúcar (GL 10-20)", gl_high:"⛔ Pico significativo de azúcar (GL > 20)", total_sugar:"Azúcar Total", net_carbs:"Carbohidratos Netos", fiber:"Fibra", glucose_response:"Respuesta de Glucosa", detected_foods:"Alimentos Detectados", tips:"💡 Consejos", disclaimer:"Este análisis no es consejo médico.", error_image:"Solo archivos de imagen", error_size:"La imagen debe ser menor de 5MB", error_failed:"Análisis fallido", peak:"📈" },
  fr: { badge:"La première app mondiale de suivi du glucose par IA", upload:"Télécharger une photo de repas", drop:"ou glisser-déposer", context_placeholder:"Contexte supplémentaire (optionnel)", analyze_btn:"🔬 Analyser Sucre & Glucose", analyzing:"⏳ Analyse en cours...", low_risk:"Risque Faible", medium_risk:"Risque Modéré", high_risk:"Risque Élevé", gl_low:"✓ Impact minimal sur la glycémie (GL < 10)", gl_medium:"⚠ Impact modéré sur la glycémie (GL 10-20)", gl_high:"⛔ Pic glycémique significatif (GL > 20)", total_sugar:"Sucre Total", net_carbs:"Glucides Nets", fiber:"Fibres", glucose_response:"Réponse Glycémique", detected_foods:"Aliments Détectés", tips:"💡 Conseils", disclaimer:"Cette analyse n'est pas un avis médical.", error_image:"Seuls les fichiers image", error_size:"L'image doit être inférieure à 5 Mo", error_failed:"Analyse échouée", peak:"📈" },
  ar: { badge:"أول تطبيق عالمي لتتبع الجلوكوز بالذكاء الاصطناعي", upload:"ارفع صورة الوجبة", drop:"أو اسحب وأفلت", context_placeholder:"معلومات إضافية (اختياري)", analyze_btn:"🔬 تحليل السكر والجلوكوز", analyzing:"⏳ جارٍ التحليل...", low_risk:"خطر منخفض", medium_risk:"خطر متوسط", high_risk:"خطر عالٍ", gl_low:"✓ تأثير ضئيل على سكر الدم (GL < 10)", gl_medium:"⚠ تأثير متوسط على سكر الدم (GL 10-20)", gl_high:"⛔ ارتفاع كبير في سكر الدم (GL > 20)", total_sugar:"السكر الكلي", net_carbs:"الكربوهيدرات الصافية", fiber:"الألياف", glucose_response:"استجابة الجلوكوز", detected_foods:"الأطعمة المكتشفة", tips:"💡 نصائح", disclaimer:"هذا التحليل ليس نصيحة طبية.", error_image:"يُقبل فقط ملفات الصور", error_size:"يجب أن تكون الصورة أقل من 5 ميجابايت", error_failed:"فشل التحليل", peak:"📈" },
  pt: { badge:"O primeiro app mundial de rastreamento de glicose com IA", upload:"Enviar foto da refeição", drop:"ou arraste e solte", context_placeholder:"Contexto adicional (opcional)", analyze_btn:"🔬 Analisar Açúcar & Glicose", analyzing:"⏳ Analisando...", low_risk:"Baixo Risco", medium_risk:"Risco Médio", high_risk:"Alto Risco", gl_low:"✓ Impacto mínimo no açúcar (GL < 10)", gl_medium:"⚠ Impacto moderado no açúcar (GL 10-20)", gl_high:"⛔ Pico significativo de açúcar (GL > 20)", total_sugar:"Açúcar Total", net_carbs:"Carboidratos Líquidos", fiber:"Fibra", glucose_response:"Resposta da Glicose", detected_foods:"Alimentos Detectados", tips:"💡 Dicas", disclaimer:"Esta análise não é conselho médico.", error_image:"Apenas arquivos de imagem", error_size:"A imagem deve ter menos de 5MB", error_failed:"Análise falhou", peak:"📈" },
  ru: { badge:"Первое в мире приложение для отслеживания глюкозы с ИИ", upload:"Загрузить фото блюда", drop:"или перетащите файл", context_placeholder:"Дополнительная информация (необязательно)", analyze_btn:"🔬 Анализ сахара и глюкозы", analyzing:"⏳ Анализируется...", low_risk:"Низкий риск", medium_risk:"Средний риск", high_risk:"Высокий риск", gl_low:"✓ Минимальное влияние на сахар (GL < 10)", gl_medium:"⚠ Умеренное влияние на сахар (GL 10-20)", gl_high:"⛔ Значительный скачок сахара (GL > 20)", total_sugar:"Всего сахара", net_carbs:"Чистые углеводы", fiber:"Клетчатка", glucose_response:"Гликемический ответ", detected_foods:"Обнаруженные продукты", tips:"💡 Советы", disclaimer:"Этот анализ не является медицинской консультацией.", error_image:"Только файлы изображений", error_size:"Изображение менее 5 МБ", error_failed:"Анализ не удался", peak:"📈" },
  de: { badge:"Die weltweit erste KI-Glukose-Tracking-App", upload:"Essensfoto hochladen", drop:"oder per Drag & Drop", context_placeholder:"Zusätzlicher Kontext (optional)", analyze_btn:"🔬 Zucker & Glukose analysieren", analyzing:"⏳ Wird analysiert...", low_risk:"Geringes Risiko", medium_risk:"Mittleres Risiko", high_risk:"Hohes Risiko", gl_low:"✓ Minimale Auswirkung auf Blutzucker (GL < 10)", gl_medium:"⚠ Moderate Auswirkung auf Blutzucker (GL 10-20)", gl_high:"⛔ Signifikanter Blutzuckeranstieg (GL > 20)", total_sugar:"Gesamtzucker", net_carbs:"Netto-Kohlenhydrate", fiber:"Ballaststoffe", glucose_response:"Glukoseantwort", detected_foods:"Erkannte Lebensmittel", tips:"💡 Tipps", disclaimer:"Diese Analyse ist kein medizinischer Rat.", error_image:"Nur Bilddateien", error_size:"Bild muss kleiner als 5 MB sein", error_failed:"Analyse fehlgeschlagen", peak:"📈" },
};
export function detectBrowserLang(): Lang {
  if (typeof navigator === "undefined") return "en";
  const lang = navigator.language.slice(0, 2).toLowerCase();
  return (lang in LANGUAGES ? lang : "en") as Lang;
}
