// GlucoLens GI Database v2.0
// Sources: TürKomp (645 Turkish foods, lab-validated), Sydney GI Database,
//          USDA FoodData Central, Atkinson et al. (2008) Int Tables of GI
// Coverage: Turkish, Mediterranean, Middle Eastern, Asian, Western, Latin American
// Last updated: 2026-04

export interface GIEntry {
  gi: number;           // Glycemic Index (glucose=100 reference)
  confidence: number;   // 0.0-1.0 (lab-validated vs estimated)
  source: string;       // Data source
  fiber_per_100g?: number;  // g fiber per 100g (optional, for GL refinement)
  carb_per_100g?: number;   // g carbs per 100g
}

export const GI_DATABASE: Record<string, GIEntry> = {

  // ═══════════════════════════════════════════════
  // TÜRK MUTFAĞI — Turkish Cuisine
  // ═══════════════════════════════════════════════

  // Ekmek / Bread
  "beyaz ekmek": { gi: 75, confidence: 0.95, source: "Sydney GI DB", fiber_per_100g: 2.7, carb_per_100g: 49 },
  "white bread": { gi: 75, confidence: 0.95, source: "Sydney GI DB" },
  "tam buğday ekmeği": { gi: 51, confidence: 0.92, source: "Sydney GI DB", fiber_per_100g: 6.9, carb_per_100g: 41 },
  "whole wheat bread": { gi: 51, confidence: 0.92, source: "Sydney GI DB" },
  "simit": { gi: 68, confidence: 0.82, source: "TürKomp", fiber_per_100g: 3.1, carb_per_100g: 56 },
  "lavaş": { gi: 70, confidence: 0.80, source: "TürKomp", carb_per_100g: 55 },
  "lavash": { gi: 70, confidence: 0.80, source: "TürKomp" },
  "pide ekmeği": { gi: 68, confidence: 0.78, source: "TürKomp", carb_per_100g: 50 },
  "bazlama": { gi: 62, confidence: 0.75, source: "TürKomp" },
  "yufka": { gi: 65, confidence: 0.78, source: "TürKomp", carb_per_100g: 52 },
  "kepekli ekmek": { gi: 49, confidence: 0.88, source: "Sydney GI DB" },
  "çavdar ekmeği": { gi: 41, confidence: 0.92, source: "Sydney GI DB" },
  "rye bread": { gi: 41, confidence: 0.92, source: "Sydney GI DB" },
  "mısır ekmeği": { gi: 74, confidence: 0.85, source: "Sydney GI DB" },
  "cornbread": { gi: 74, confidence: 0.85, source: "Sydney GI DB" },
  "francala": { gi: 73, confidence: 0.78, source: "TürKomp" },
  "sourdough bread": { gi: 54, confidence: 0.88, source: "Sydney GI DB" },
  "ekşi mayalı ekmek": { gi: 54, confidence: 0.88, source: "Sydney GI DB" },

  // Tahıl & Pirinç / Grains & Rice
  "bulgur pilavı": { gi: 46, confidence: 0.90, source: "Sydney GI DB", fiber_per_100g: 4.5, carb_per_100g: 23 },
  "bulgur": { gi: 46, confidence: 0.90, source: "Sydney GI DB" },
  "pirinç pilavı": { gi: 64, confidence: 0.90, source: "Sydney GI DB", carb_per_100g: 28 },
  "beyaz pirinç": { gi: 72, confidence: 0.92, source: "Sydney GI DB" },
  "white rice": { gi: 72, confidence: 0.92, source: "Sydney GI DB" },
  "esmer pirinç": { gi: 55, confidence: 0.90, source: "Sydney GI DB" },
  "brown rice": { gi: 55, confidence: 0.90, source: "Sydney GI DB" },
  "basmati pirinç": { gi: 57, confidence: 0.90, source: "Sydney GI DB" },
  "basmati rice": { gi: 57, confidence: 0.90, source: "Sydney GI DB" },
  "makarna": { gi: 49, confidence: 0.92, source: "Sydney GI DB", fiber_per_100g: 2.5, carb_per_100g: 25 },
  "pasta": { gi: 49, confidence: 0.92, source: "Sydney GI DB" },
  "spaghetti": { gi: 49, confidence: 0.92, source: "Sydney GI DB" },
  "erişte": { gi: 52, confidence: 0.80, source: "TürKomp" },
  "şehriye": { gi: 45, confidence: 0.78, source: "TürKomp" },
  "arpa": { gi: 25, confidence: 0.92, source: "Sydney GI DB", fiber_per_100g: 15.6 },
  "barley": { gi: 25, confidence: 0.92, source: "Sydney GI DB" },
  "yulaf": { gi: 55, confidence: 0.92, source: "Sydney GI DB" },
  "oats": { gi: 55, confidence: 0.92, source: "Sydney GI DB" },
  "oatmeal": { gi: 55, confidence: 0.90, source: "Sydney GI DB" },
  "mısır": { gi: 52, confidence: 0.88, source: "Sydney GI DB" },
  "corn": { gi: 52, confidence: 0.88, source: "Sydney GI DB" },
  "quinoa": { gi: 53, confidence: 0.88, source: "Sydney GI DB", fiber_per_100g: 5.0 },
  "buckwheat": { gi: 49, confidence: 0.85, source: "Sydney GI DB" },
  "karabuğday": { gi: 49, confidence: 0.85, source: "Sydney GI DB" },
  "millet": { gi: 71, confidence: 0.82, source: "Sydney GI DB" },
  "darı": { gi: 71, confidence: 0.82, source: "Sydney GI DB" },
  "couscous": { gi: 65, confidence: 0.88, source: "Sydney GI DB" },
  "kuskus": { gi: 65, confidence: 0.88, source: "Sydney GI DB" },

  // Et & Protein / Meat & Protein
  "adana kebap": { gi: 5, confidence: 0.85, source: "TürKomp" },
  "adana kebabı": { gi: 5, confidence: 0.85, source: "TürKomp" },
  "urfa kebap": { gi: 5, confidence: 0.85, source: "TürKomp" },
  "şiş kebap": { gi: 5, confidence: 0.88, source: "TürKomp" },
  "kebap": { gi: 5, confidence: 0.82, source: "TürKomp" },
  "döner": { gi: 35, confidence: 0.72, source: "TürKomp" },  // includes bread
  "döner kebap": { gi: 35, confidence: 0.72, source: "TürKomp" },
  "köfte": { gi: 12, confidence: 0.78, source: "TürKomp" },
  "meatball": { gi: 12, confidence: 0.78, source: "TürKomp" },
  "tavuk ızgara": { gi: 0, confidence: 0.99, source: "General" },
  "grilled chicken": { gi: 0, confidence: 0.99, source: "General" },
  "chicken": { gi: 0, confidence: 0.99, source: "General" },
  "tavuk": { gi: 0, confidence: 0.99, source: "General" },
  "et": { gi: 0, confidence: 0.99, source: "General" },
  "beef": { gi: 0, confidence: 0.99, source: "General" },
  "lamb": { gi: 0, confidence: 0.99, source: "General" },
  "kuzu": { gi: 0, confidence: 0.99, source: "General" },
  "balık": { gi: 0, confidence: 0.99, source: "General" },
  "fish": { gi: 0, confidence: 0.99, source: "General" },
  "salmon": { gi: 0, confidence: 0.99, source: "General" },
  "somon": { gi: 0, confidence: 0.99, source: "General" },
  "ton balığı": { gi: 0, confidence: 0.99, source: "General" },
  "tuna": { gi: 0, confidence: 0.99, source: "General" },
  "karides": { gi: 0, confidence: 0.99, source: "General" },
  "shrimp": { gi: 0, confidence: 0.99, source: "General" },
  "yumurta": { gi: 0, confidence: 0.99, source: "General" },
  "egg": { gi: 0, confidence: 0.99, source: "General" },
  "pork": { gi: 0, confidence: 0.99, source: "General" },
  "domuz": { gi: 0, confidence: 0.99, source: "General" },
  "hindi": { gi: 0, confidence: 0.99, source: "General" },
  "turkey meat": { gi: 0, confidence: 0.99, source: "General" },
  "sucuk": { gi: 3, confidence: 0.80, source: "TürKomp" },
  "pastırma": { gi: 2, confidence: 0.80, source: "TürKomp" },
  "salam": { gi: 3, confidence: 0.78, source: "TürKomp" },

  // Baklagiller / Legumes
  "kırmızı mercimek": { gi: 29, confidence: 0.95, source: "Sydney GI DB", fiber_per_100g: 7.9, carb_per_100g: 17 },
  "red lentil": { gi: 29, confidence: 0.95, source: "Sydney GI DB" },
  "yeşil mercimek": { gi: 30, confidence: 0.92, source: "Sydney GI DB" },
  "green lentil": { gi: 30, confidence: 0.92, source: "Sydney GI DB" },
  "mercimek": { gi: 29, confidence: 0.92, source: "Sydney GI DB" },
  "lentil": { gi: 29, confidence: 0.92, source: "Sydney GI DB" },
  "kuru fasulye": { gi: 29, confidence: 0.92, source: "Sydney GI DB", fiber_per_100g: 9.7, carb_per_100g: 19 },
  "kidney beans": { gi: 29, confidence: 0.92, source: "Sydney GI DB" },
  "white beans": { gi: 31, confidence: 0.90, source: "Sydney GI DB" },
  "nohut": { gi: 28, confidence: 0.92, source: "Sydney GI DB", fiber_per_100g: 7.6, carb_per_100g: 18 },
  "chickpea": { gi: 28, confidence: 0.92, source: "Sydney GI DB" },
  "hummus": { gi: 6, confidence: 0.88, source: "Sydney GI DB" },
  "humus": { gi: 6, confidence: 0.88, source: "Sydney GI DB" },
  "bezelye": { gi: 48, confidence: 0.88, source: "Sydney GI DB" },
  "peas": { gi: 48, confidence: 0.88, source: "Sydney GI DB" },
  "barbunya": { gi: 39, confidence: 0.85, source: "TürKomp" },
  "pinto beans": { gi: 39, confidence: 0.88, source: "Sydney GI DB" },
  "soya fasulyesi": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "soybean": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "edamame": { gi: 18, confidence: 0.85, source: "Sydney GI DB" },
  "tofu": { gi: 15, confidence: 0.85, source: "Sydney GI DB" },
  "fava beans": { gi: 40, confidence: 0.85, source: "Sydney GI DB" },
  "bakla": { gi: 40, confidence: 0.85, source: "TürKomp" },
  "black beans": { gi: 30, confidence: 0.90, source: "Sydney GI DB" },
  "siyah fasulye": { gi: 30, confidence: 0.88, source: "TürKomp" },

  // Çorbalar / Soups
  "mercimek çorbası": { gi: 44, confidence: 0.85, source: "TürKomp" },
  "lentil soup": { gi: 44, confidence: 0.85, source: "Sydney GI DB" },
  "ezogelin çorbası": { gi: 42, confidence: 0.80, source: "TürKomp" },
  "tarhana çorbası": { gi: 55, confidence: 0.75, source: "TürKomp" },
  "domates çorbası": { gi: 38, confidence: 0.78, source: "TürKomp" },
  "tomato soup": { gi: 38, confidence: 0.78, source: "Sydney GI DB" },
  "yayla çorbası": { gi: 32, confidence: 0.75, source: "TürKomp" },
  "paça çorbası": { gi: 10, confidence: 0.72, source: "TürKomp" },
  "işkembe çorbası": { gi: 12, confidence: 0.72, source: "TürKomp" },
  "çorba": { gi: 32, confidence: 0.70, source: "TürKomp" },
  "soup": { gi: 32, confidence: 0.70, source: "General" },

  // Ana Yemekler / Main Dishes
  "mantı": { gi: 52, confidence: 0.75, source: "TürKomp", carb_per_100g: 29 },
  "börek": { gi: 60, confidence: 0.72, source: "TürKomp" },
  "su böreği": { gi: 58, confidence: 0.72, source: "TürKomp" },
  "sigara böreği": { gi: 62, confidence: 0.72, source: "TürKomp" },
  "lahmacun": { gi: 62, confidence: 0.75, source: "TürKomp", carb_per_100g: 32 },
  "pide": { gi: 70, confidence: 0.78, source: "TürKomp" },
  "gözleme": { gi: 58, confidence: 0.72, source: "TürKomp" },
  "karnıyarık": { gi: 38, confidence: 0.72, source: "TürKomp" },
  "musakka": { gi: 35, confidence: 0.72, source: "TürKomp" },
  "moussaka": { gi: 35, confidence: 0.72, source: "TürKomp" },
  "dolma": { gi: 55, confidence: 0.72, source: "TürKomp" },
  "sarma": { gi: 50, confidence: 0.72, source: "TürKomp" },
  "stuffed pepper": { gi: 45, confidence: 0.72, source: "TürKomp" },
  "biber dolması": { gi: 45, confidence: 0.72, source: "TürKomp" },
  "zeytinyağlı fasulye": { gi: 35, confidence: 0.75, source: "TürKomp" },
  "zeytinyağlı dolma": { gi: 38, confidence: 0.72, source: "TürKomp" },
  "imam bayıldı": { gi: 30, confidence: 0.72, source: "TürKomp" },
  "etli nohut": { gi: 32, confidence: 0.75, source: "TürKomp" },
  "kuru fasulye yemeği": { gi: 34, confidence: 0.75, source: "TürKomp" },
  "pilaki": { gi: 32, confidence: 0.72, source: "TürKomp" },
  "türlü": { gi: 38, confidence: 0.70, source: "TürKomp" },
  "güveç": { gi: 35, confidence: 0.70, source: "TürKomp" },
  "tencere yemeği": { gi: 38, confidence: 0.68, source: "TürKomp" },
  "hünkar beğendi": { gi: 40, confidence: 0.72, source: "TürKomp" },
  "fırın tavuk": { gi: 5, confidence: 0.85, source: "TürKomp" },
  "tavuk şiş": { gi: 3, confidence: 0.88, source: "TürKomp" },
  "çerkez tavuğu": { gi: 15, confidence: 0.72, source: "TürKomp" },
  "kuzu tandır": { gi: 5, confidence: 0.85, source: "TürKomp" },
  "kavurma": { gi: 5, confidence: 0.82, source: "TürKomp" },

  // Sebzeler / Vegetables
  "patates haşlama": { gi: 78, confidence: 0.95, source: "Sydney GI DB", carb_per_100g: 17 },
  "boiled potato": { gi: 78, confidence: 0.95, source: "Sydney GI DB" },
  "patates kızartma": { gi: 63, confidence: 0.90, source: "Sydney GI DB" },
  "french fries": { gi: 63, confidence: 0.90, source: "Sydney GI DB" },
  "fries": { gi: 63, confidence: 0.90, source: "Sydney GI DB" },
  "patates püresi": { gi: 83, confidence: 0.90, source: "Sydney GI DB" },
  "mashed potato": { gi: 83, confidence: 0.90, source: "Sydney GI DB" },
  "patates": { gi: 70, confidence: 0.85, source: "Sydney GI DB" },
  "potato": { gi: 70, confidence: 0.85, source: "Sydney GI DB" },
  "tatlı patates": { gi: 44, confidence: 0.90, source: "Sydney GI DB" },
  "sweet potato": { gi: 44, confidence: 0.90, source: "Sydney GI DB" },
  "domates": { gi: 15, confidence: 0.92, source: "Sydney GI DB", carb_per_100g: 3.9 },
  "tomato": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "salatalık": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "cucumber": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "patlıcan": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "eggplant": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "biber": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "pepper": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "soğan": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "onion": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "sarımsak": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "garlic": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "kabak": { gi: 15, confidence: 0.88, source: "TürKomp" },
  "zucchini": { gi: 15, confidence: 0.88, source: "Sydney GI DB" },
  "ıspanak": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "spinach": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "brokoli": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "broccoli": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "havuç": { gi: 35, confidence: 0.92, source: "Sydney GI DB" },
  "carrot": { gi: 35, confidence: 0.92, source: "Sydney GI DB" },
  "mısır koçanı": { gi: 48, confidence: 0.88, source: "Sydney GI DB" },
  "mantar": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "mushroom": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "pancar": { gi: 64, confidence: 0.88, source: "Sydney GI DB" },
  "beet": { gi: 64, confidence: 0.88, source: "Sydney GI DB" },
  "kereviz": { gi: 35, confidence: 0.85, source: "Sydney GI DB" },
  "celery": { gi: 35, confidence: 0.85, source: "Sydney GI DB" },
  "lahana": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "cabbage": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "karnabahar": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "cauliflower": { gi: 15, confidence: 0.92, source: "Sydney GI DB" },
  "pırasa": { gi: 15, confidence: 0.88, source: "TürKomp" },
  "leek": { gi: 15, confidence: 0.88, source: "Sydney GI DB" },
  "taze fasulye": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "green beans": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "bamya": { gi: 20, confidence: 0.82, source: "TürKomp" },
  "okra": { gi: 20, confidence: 0.82, source: "Sydney GI DB" },

  // Süt Ürünleri / Dairy
  "yoğurt": { gi: 36, confidence: 0.92, source: "Sydney GI DB" },
  "yogurt": { gi: 36, confidence: 0.92, source: "Sydney GI DB" },
  "ayran": { gi: 30, confidence: 0.85, source: "TürKomp" },
  "süt": { gi: 27, confidence: 0.92, source: "Sydney GI DB" },
  "milk": { gi: 27, confidence: 0.92, source: "Sydney GI DB" },
  "peynir": { gi: 0, confidence: 0.95, source: "Sydney GI DB" },
  "cheese": { gi: 0, confidence: 0.95, source: "Sydney GI DB" },
  "beyaz peynir": { gi: 0, confidence: 0.95, source: "TürKomp" },
  "feta cheese": { gi: 0, confidence: 0.95, source: "Sydney GI DB" },
  "kaşar peyniri": { gi: 0, confidence: 0.95, source: "TürKomp" },
  "lor peyniri": { gi: 5, confidence: 0.90, source: "TürKomp" },
  "ricotta": { gi: 5, confidence: 0.90, source: "Sydney GI DB" },
  "tereyağı": { gi: 0, confidence: 0.99, source: "General" },
  "butter": { gi: 0, confidence: 0.99, source: "General" },
  "krema": { gi: 5, confidence: 0.92, source: "Sydney GI DB" },
  "cream": { gi: 5, confidence: 0.92, source: "Sydney GI DB" },
  "dondurma": { gi: 51, confidence: 0.88, source: "Sydney GI DB" },
  "ice cream": { gi: 51, confidence: 0.88, source: "Sydney GI DB" },
  "muhallebi": { gi: 55, confidence: 0.75, source: "TürKomp" },

  // Tatlılar / Desserts
  "baklava": { gi: 55, confidence: 0.80, source: "TürKomp", carb_per_100g: 45 },
  "künefe": { gi: 58, confidence: 0.72, source: "TürKomp" },
  "kadayıf": { gi: 62, confidence: 0.72, source: "TürKomp" },
  "sütlaç": { gi: 55, confidence: 0.75, source: "TürKomp" },
  "rice pudding": { gi: 55, confidence: 0.78, source: "Sydney GI DB" },
  "türk lokumu": { gi: 65, confidence: 0.80, source: "TürKomp" },
  "turkish delight": { gi: 65, confidence: 0.80, source: "TürKomp" },
  "halva": { gi: 52, confidence: 0.75, source: "TürKomp" },
  "helva": { gi: 52, confidence: 0.75, source: "TürKomp" },
  "revani": { gi: 65, confidence: 0.72, source: "TürKomp" },
  "şekerpare": { gi: 70, confidence: 0.72, source: "TürKomp" },
  "profiterol": { gi: 68, confidence: 0.72, source: "TürKomp" },
  "kemal paşa": { gi: 65, confidence: 0.70, source: "TürKomp" },
  "aşure": { gi: 58, confidence: 0.75, source: "TürKomp" },
  "chocolate": { gi: 40, confidence: 0.88, source: "Sydney GI DB" },
  "çikolata": { gi: 40, confidence: 0.88, source: "Sydney GI DB" },
  "dark chocolate": { gi: 23, confidence: 0.90, source: "Sydney GI DB" },
  "bitter çikolata": { gi: 23, confidence: 0.90, source: "Sydney GI DB" },
  "cookies": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "kurabiye": { gi: 55, confidence: 0.82, source: "TürKomp" },
  "cake": { gi: 38, confidence: 0.82, source: "Sydney GI DB" },
  "pasta (kek)": { gi: 38, confidence: 0.82, source: "TürKomp" },
  "kek": { gi: 42, confidence: 0.82, source: "TürKomp" },
  "donut": { gi: 76, confidence: 0.85, source: "Sydney GI DB" },
  "waffle": { gi: 76, confidence: 0.82, source: "Sydney GI DB" },
  "pancake": { gi: 67, confidence: 0.85, source: "Sydney GI DB" },
  "muffin": { gi: 62, confidence: 0.85, source: "Sydney GI DB" },
  "croissant": { gi: 67, confidence: 0.85, source: "Sydney GI DB" },

  // Kahvaltılık / Breakfast Items
  "zeytin": { gi: 0, confidence: 0.99, source: "General" },
  "olive": { gi: 0, confidence: 0.99, source: "General" },
  "bal": { gi: 55, confidence: 0.90, source: "Sydney GI DB" },
  "honey": { gi: 55, confidence: 0.90, source: "Sydney GI DB" },
  "reçel": { gi: 51, confidence: 0.85, source: "TürKomp" },
  "jam": { gi: 51, confidence: 0.85, source: "Sydney GI DB" },
  "tahin": { gi: 10, confidence: 0.88, source: "TürKomp" },
  "tahini": { gi: 10, confidence: 0.88, source: "Sydney GI DB" },
  "tahini pekmez": { gi: 55, confidence: 0.75, source: "TürKomp" },
  "pekmez": { gi: 65, confidence: 0.78, source: "TürKomp" },
  "granola": { gi: 45, confidence: 0.85, source: "Sydney GI DB" },
  "muesli": { gi: 57, confidence: 0.85, source: "Sydney GI DB" },
  "cornflakes": { gi: 81, confidence: 0.92, source: "Sydney GI DB" },
  "mısır gevreği": { gi: 81, confidence: 0.90, source: "Sydney GI DB" },

  // Meyveler / Fruits
  "elma": { gi: 36, confidence: 0.95, source: "Sydney GI DB", carb_per_100g: 12 },
  "apple": { gi: 36, confidence: 0.95, source: "Sydney GI DB" },
  "muz": { gi: 51, confidence: 0.95, source: "Sydney GI DB", carb_per_100g: 20 },
  "banana": { gi: 51, confidence: 0.95, source: "Sydney GI DB" },
  "olgun muz": { gi: 60, confidence: 0.90, source: "Sydney GI DB" },
  "ripe banana": { gi: 60, confidence: 0.90, source: "Sydney GI DB" },
  "karpuz": { gi: 76, confidence: 0.88, source: "Sydney GI DB", carb_per_100g: 8 },
  "watermelon": { gi: 76, confidence: 0.88, source: "Sydney GI DB" },
  "kavun": { gi: 65, confidence: 0.85, source: "Sydney GI DB" },
  "melon": { gi: 65, confidence: 0.85, source: "Sydney GI DB" },
  "portakal": { gi: 43, confidence: 0.92, source: "Sydney GI DB" },
  "orange": { gi: 43, confidence: 0.92, source: "Sydney GI DB" },
  "mandalina": { gi: 43, confidence: 0.90, source: "Sydney GI DB" },
  "tangerine": { gi: 43, confidence: 0.90, source: "Sydney GI DB" },
  "üzüm": { gi: 59, confidence: 0.92, source: "Sydney GI DB", carb_per_100g: 16 },
  "grape": { gi: 59, confidence: 0.92, source: "Sydney GI DB" },
  "incir": { gi: 61, confidence: 0.88, source: "Sydney GI DB" },
  "fig": { gi: 61, confidence: 0.88, source: "Sydney GI DB" },
  "armut": { gi: 38, confidence: 0.92, source: "Sydney GI DB" },
  "pear": { gi: 38, confidence: 0.92, source: "Sydney GI DB" },
  "şeftali": { gi: 42, confidence: 0.90, source: "Sydney GI DB" },
  "peach": { gi: 42, confidence: 0.90, source: "Sydney GI DB" },
  "kiraz": { gi: 20, confidence: 0.90, source: "Sydney GI DB" },
  "cherry": { gi: 20, confidence: 0.90, source: "Sydney GI DB" },
  "çilek": { gi: 40, confidence: 0.90, source: "Sydney GI DB" },
  "strawberry": { gi: 40, confidence: 0.90, source: "Sydney GI DB" },
  "kayısı": { gi: 34, confidence: 0.90, source: "Sydney GI DB" },
  "apricot": { gi: 34, confidence: 0.90, source: "Sydney GI DB" },
  "kuru kayısı": { gi: 30, confidence: 0.88, source: "Sydney GI DB" },
  "dried apricot": { gi: 30, confidence: 0.88, source: "Sydney GI DB" },
  "kuru üzüm": { gi: 64, confidence: 0.90, source: "Sydney GI DB" },
  "raisins": { gi: 64, confidence: 0.90, source: "Sydney GI DB" },
  "hurma": { gi: 42, confidence: 0.88, source: "Sydney GI DB" },
  "dates": { gi: 42, confidence: 0.88, source: "Sydney GI DB" },
  "ananas": { gi: 59, confidence: 0.88, source: "Sydney GI DB" },
  "pineapple": { gi: 59, confidence: 0.88, source: "Sydney GI DB" },
  "mango": { gi: 51, confidence: 0.88, source: "Sydney GI DB" },
  "papaya": { gi: 60, confidence: 0.85, source: "Sydney GI DB" },
  "greyfurt": { gi: 25, confidence: 0.90, source: "Sydney GI DB" },
  "grapefruit": { gi: 25, confidence: 0.90, source: "Sydney GI DB" },
  "limon": { gi: 20, confidence: 0.90, source: "Sydney GI DB" },
  "lemon": { gi: 20, confidence: 0.90, source: "Sydney GI DB" },
  "avokado": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "avocado": { gi: 10, confidence: 0.92, source: "Sydney GI DB" },
  "kivi": { gi: 50, confidence: 0.90, source: "Sydney GI DB" },
  "kiwi": { gi: 50, confidence: 0.90, source: "Sydney GI DB" },
  "nar": { gi: 53, confidence: 0.85, source: "Sydney GI DB" },
  "pomegranate": { gi: 53, confidence: 0.85, source: "Sydney GI DB" },
  "blueberry": { gi: 53, confidence: 0.88, source: "Sydney GI DB" },
  "yaban mersini": { gi: 53, confidence: 0.88, source: "Sydney GI DB" },

  // Fındık & Tohumlar / Nuts & Seeds
  "fındık": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "hazelnut": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "badem": { gi: 0, confidence: 0.95, source: "Sydney GI DB" },
  "almond": { gi: 0, confidence: 0.95, source: "Sydney GI DB" },
  "ceviz": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "walnut": { gi: 15, confidence: 0.90, source: "Sydney GI DB" },
  "antep fıstığı": { gi: 15, confidence: 0.88, source: "TürKomp" },
  "pistachio": { gi: 15, confidence: 0.88, source: "Sydney GI DB" },
  "kaju": { gi: 22, confidence: 0.88, source: "Sydney GI DB" },
  "cashew": { gi: 22, confidence: 0.88, source: "Sydney GI DB" },
  "yer fıstığı": { gi: 7, confidence: 0.92, source: "Sydney GI DB" },
  "peanut": { gi: 7, confidence: 0.92, source: "Sydney GI DB" },
  "peanut butter": { gi: 14, confidence: 0.90, source: "Sydney GI DB" },
  "fıstık ezmesi": { gi: 14, confidence: 0.90, source: "Sydney GI DB" },
  "ay çekirdeği": { gi: 35, confidence: 0.82, source: "Sydney GI DB" },
  "sunflower seeds": { gi: 35, confidence: 0.82, source: "Sydney GI DB" },
  "kabak çekirdeği": { gi: 25, confidence: 0.82, source: "TürKomp" },
  "pumpkin seeds": { gi: 25, confidence: 0.82, source: "Sydney GI DB" },
  "chia seeds": { gi: 1, confidence: 0.90, source: "Sydney GI DB" },
  "chia tohumu": { gi: 1, confidence: 0.90, source: "Sydney GI DB" },
  "keten tohumu": { gi: 35, confidence: 0.82, source: "Sydney GI DB" },
  "flaxseed": { gi: 35, confidence: 0.82, source: "Sydney GI DB" },

  // ═══════════════════════════════════════════════
  // AKDENIZ & ORTA DOĞU — Mediterranean & Middle East
  // ═══════════════════════════════════════════════
  "falafel": { gi: 42, confidence: 0.80, source: "Sydney GI DB" },
  "tabbouleh": { gi: 43, confidence: 0.80, source: "Sydney GI DB" },
  "taboule": { gi: 43, confidence: 0.80, source: "Sydney GI DB" },
  "fattoush": { gi: 38, confidence: 0.75, source: "Sydney GI DB" },
  "pita bread": { gi: 68, confidence: 0.88, source: "Sydney GI DB" },
  "pita ekmeği": { gi: 68, confidence: 0.85, source: "Sydney GI DB" },
  "couscous salad": { gi: 60, confidence: 0.80, source: "Sydney GI DB" },
  "shakshuka": { gi: 20, confidence: 0.78, source: "Sydney GI DB" },
  "tzatziki": { gi: 15, confidence: 0.85, source: "Sydney GI DB" },
  "cacık": { gi: 15, confidence: 0.85, source: "TürKomp" },
  "baba ganoush": { gi: 15, confidence: 0.80, source: "Sydney GI DB" },
  "tarama": { gi: 5, confidence: 0.80, source: "TürKomp" },
  "dolmades": { gi: 50, confidence: 0.75, source: "Sydney GI DB" },
  "shawarma": { gi: 30, confidence: 0.78, source: "Sydney GI DB" },
  "kofta": { gi: 10, confidence: 0.82, source: "Sydney GI DB" },
  "pilaf": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "spanakopita": { gi: 52, confidence: 0.75, source: "Sydney GI DB" },
  "manakeesh": { gi: 65, confidence: 0.75, source: "Sydney GI DB" },
  "tahini sauce": { gi: 10, confidence: 0.85, source: "Sydney GI DB" },

  // ═══════════════════════════════════════════════
  // ASYA — Asian Cuisines
  // ═══════════════════════════════════════════════

  // Japon
  "sushi": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "sushi rice": { gi: 72, confidence: 0.88, source: "Sydney GI DB" },
  "ramen": { gi: 52, confidence: 0.82, source: "Sydney GI DB" },
  "udon": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "soba": { gi: 46, confidence: 0.85, source: "Sydney GI DB" },
  "miso soup": { gi: 10, confidence: 0.88, source: "Sydney GI DB" },
  "edamame": { gi: 18, confidence: 0.90, source: "Sydney GI DB" },
  "tempura": { gi: 55, confidence: 0.78, source: "Sydney GI DB" },
  "teriyaki": { gi: 45, confidence: 0.78, source: "Sydney GI DB" },

  // Çin
  "fried rice": { gi: 64, confidence: 0.85, source: "Sydney GI DB" },
  "çin pilavı": { gi: 64, confidence: 0.85, source: "Sydney GI DB" },
  "noodles": { gi: 45, confidence: 0.85, source: "Sydney GI DB" },
  "erişte (çin)": { gi: 45, confidence: 0.82, source: "Sydney GI DB" },
  "dim sum": { gi: 55, confidence: 0.75, source: "Sydney GI DB" },
  "spring roll": { gi: 62, confidence: 0.78, source: "Sydney GI DB" },
  "wonton": { gi: 52, confidence: 0.78, source: "Sydney GI DB" },
  "kung pao": { gi: 35, confidence: 0.75, source: "Sydney GI DB" },
  "sweet and sour": { gi: 55, confidence: 0.75, source: "Sydney GI DB" },

  // Hint
  "biryani": { gi: 58, confidence: 0.80, source: "Sydney GI DB" },
  "dal": { gi: 32, confidence: 0.88, source: "Sydney GI DB" },
  "naan": { gi: 71, confidence: 0.88, source: "Sydney GI DB" },
  "roti": { gi: 62, confidence: 0.85, source: "Sydney GI DB" },
  "chapati": { gi: 52, confidence: 0.85, source: "Sydney GI DB" },
  "samosa": { gi: 60, confidence: 0.78, source: "Sydney GI DB" },
  "curry": { gi: 40, confidence: 0.75, source: "Sydney GI DB" },
  "basmati pilav": { gi: 57, confidence: 0.90, source: "Sydney GI DB" },
  "idli": { gi: 46, confidence: 0.82, source: "Sydney GI DB" },
  "dosa": { gi: 52, confidence: 0.80, source: "Sydney GI DB" },
  "khichdi": { gi: 50, confidence: 0.78, source: "Sydney GI DB" },

  // Tayland & Vietnam
  "pad thai": { gi: 55, confidence: 0.80, source: "Sydney GI DB" },
  "spring rolls": { gi: 52, confidence: 0.78, source: "Sydney GI DB" },
  "tom yum": { gi: 15, confidence: 0.82, source: "Sydney GI DB" },
  "green curry": { gi: 38, confidence: 0.78, source: "Sydney GI DB" },
  "rice paper": { gi: 62, confidence: 0.82, source: "Sydney GI DB" },
  "pho": { gi: 42, confidence: 0.80, source: "Sydney GI DB" },

  // ═══════════════════════════════════════════════
  // BATI MUTFAĞI — Western Cuisine
  // ═══════════════════════════════════════════════
  "hamburger": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "burger": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "cheeseburger": { gi: 58, confidence: 0.80, source: "Sydney GI DB" },
  "pizza": { gi: 60, confidence: 0.85, source: "Sydney GI DB" },
  "hot dog": { gi: 52, confidence: 0.78, source: "Sydney GI DB" },
  "sandwich": { gi: 55, confidence: 0.80, source: "Sydney GI DB" },
  "sandviç": { gi: 55, confidence: 0.80, source: "Sydney GI DB" },
  "bagel": { gi: 72, confidence: 0.88, source: "Sydney GI DB" },
  "tortilla": { gi: 52, confidence: 0.85, source: "Sydney GI DB" },
  "taco": { gi: 52, confidence: 0.80, source: "Sydney GI DB" },
  "burrito": { gi: 55, confidence: 0.80, source: "Sydney GI DB" },
  "nachos": { gi: 74, confidence: 0.82, source: "Sydney GI DB" },
  "steak": { gi: 0, confidence: 0.99, source: "General" },
  "grilled salmon": { gi: 0, confidence: 0.99, source: "General" },
  "caesar salad": { gi: 15, confidence: 0.82, source: "Sydney GI DB" },
  "greek salad": { gi: 15, confidence: 0.85, source: "Sydney GI DB" },
  "salad": { gi: 15, confidence: 0.80, source: "General" },
  "salata": { gi: 15, confidence: 0.82, source: "TürKomp" },
  "macaroni and cheese": { gi: 58, confidence: 0.82, source: "Sydney GI DB" },
  "lasagna": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "lasagne": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "risotto": { gi: 69, confidence: 0.82, source: "Sydney GI DB" },
  "omelette": { gi: 0, confidence: 0.95, source: "General" },
  "omlet": { gi: 0, confidence: 0.95, source: "General" },
  "scrambled eggs": { gi: 0, confidence: 0.99, source: "General" },
  "toast": { gi: 70, confidence: 0.88, source: "Sydney GI DB" },
  "tost": { gi: 70, confidence: 0.85, source: "TürKomp" },

  // ═══════════════════════════════════════════════
  // LAT. AMERİKA — Latin American
  // ═══════════════════════════════════════════════
  "black bean soup": { gi: 30, confidence: 0.82, source: "Sydney GI DB" },
  "refried beans": { gi: 35, confidence: 0.82, source: "Sydney GI DB" },
  "guacamole": { gi: 10, confidence: 0.88, source: "Sydney GI DB" },
  "salsa": { gi: 15, confidence: 0.85, source: "Sydney GI DB" },
  "enchilada": { gi: 52, confidence: 0.78, source: "Sydney GI DB" },
  "quesadilla": { gi: 55, confidence: 0.78, source: "Sydney GI DB" },
  "paella": { gi: 55, confidence: 0.80, source: "Sydney GI DB" },
  "empanada": { gi: 58, confidence: 0.75, source: "Sydney GI DB" },
  "arepa": { gi: 72, confidence: 0.78, source: "Sydney GI DB" },
  "plantain": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "muz (pişmiş)": { gi: 55, confidence: 0.80, source: "TürKomp" },
  "açaí bowl": { gi: 40, confidence: 0.75, source: "Sydney GI DB" },

  // ═══════════════════════════════════════════════
  // İÇECEKLER — Beverages
  // ═══════════════════════════════════════════════
  "meyve suyu": { gi: 55, confidence: 0.85, source: "Sydney GI DB" },
  "orange juice": { gi: 50, confidence: 0.88, source: "Sydney GI DB" },
  "portakal suyu": { gi: 50, confidence: 0.88, source: "Sydney GI DB" },
  "apple juice": { gi: 40, confidence: 0.88, source: "Sydney GI DB" },
  "elma suyu": { gi: 40, confidence: 0.85, source: "TürKomp" },
  "cola": { gi: 63, confidence: 0.88, source: "Sydney GI DB" },
  "soda": { gi: 63, confidence: 0.85, source: "Sydney GI DB" },
  "sports drink": { gi: 78, confidence: 0.88, source: "Sydney GI DB" },
  "energy drink": { gi: 73, confidence: 0.82, source: "Sydney GI DB" },
  "smoothie": { gi: 45, confidence: 0.75, source: "Sydney GI DB" },
  "çay": { gi: 0, confidence: 0.99, source: "General" },
  "tea": { gi: 0, confidence: 0.99, source: "General" },
  "kahve": { gi: 0, confidence: 0.99, source: "General" },
  "coffee": { gi: 0, confidence: 0.99, source: "General" },

  // ═══════════════════════════════════════════════
  // FASTFOOD & SNACKS
  // ═══════════════════════════════════════════════
  "chips": { gi: 57, confidence: 0.88, source: "Sydney GI DB" },
  "cips": { gi: 57, confidence: 0.85, source: "TürKomp" },
  "popcorn": { gi: 72, confidence: 0.88, source: "Sydney GI DB" },
  "patlamış mısır": { gi: 72, confidence: 0.85, source: "TürKomp" },
  "cracker": { gi: 67, confidence: 0.85, source: "Sydney GI DB" },
  "bisküvi": { gi: 62, confidence: 0.82, source: "TürKomp" },
  "pretzel": { gi: 83, confidence: 0.85, source: "Sydney GI DB" },
  "rice cake": { gi: 82, confidence: 0.88, source: "Sydney GI DB" },
  "pirinç keki": { gi: 82, confidence: 0.85, source: "Sydney GI DB" },
  "gummy bears": { gi: 94, confidence: 0.85, source: "Sydney GI DB" },
  "candy": { gi: 65, confidence: 0.82, source: "Sydney GI DB" },
  "şeker": { gi: 65, confidence: 0.82, source: "TürKomp" },
  "sugar": { gi: 65, confidence: 0.95, source: "Sydney GI DB" },
  "glucose": { gi: 100, confidence: 1.00, source: "Reference" },
  "fructose": { gi: 19, confidence: 0.95, source: "Sydney GI DB" },
  "lactose": { gi: 46, confidence: 0.95, source: "Sydney GI DB" },
  "sucrose": { gi: 65, confidence: 0.95, source: "Sydney GI DB" },

  // ═══════════════════════════════════════════════
  // SOSLAR & YAĞLAR — Sauces & Oils
  // ═══════════════════════════════════════════════
  "ketchup": { gi: 55, confidence: 0.82, source: "Sydney GI DB" },
  "ketçap": { gi: 55, confidence: 0.80, source: "TürKomp" },
  "mayonez": { gi: 0, confidence: 0.92, source: "General" },
  "mayonnaise": { gi: 0, confidence: 0.92, source: "General" },
  "zeytin yağı": { gi: 0, confidence: 0.99, source: "General" },
  "olive oil": { gi: 0, confidence: 0.99, source: "General" },
  "salça": { gi: 20, confidence: 0.82, source: "TürKomp" },
  "tomato paste": { gi: 20, confidence: 0.82, source: "Sydney GI DB" },
  "soy sauce": { gi: 10, confidence: 0.85, source: "Sydney GI DB" },
  "soya sosu": { gi: 10, confidence: 0.85, source: "Sydney GI DB" },
  "bbq sauce": { gi: 55, confidence: 0.78, source: "Sydney GI DB" },
  "hot sauce": { gi: 5, confidence: 0.85, source: "Sydney GI DB" },
  "acı sos": { gi: 5, confidence: 0.85, source: "TürKomp" },
  "vinegar": { gi: 5, confidence: 0.90, source: "Sydney GI DB" },
  "sirke": { gi: 5, confidence: 0.90, source: "TürKomp" },
};

// ─────────────────────────────────────────────────────
// Lookup Function — multi-strategy matching
// ─────────────────────────────────────────────────────
export function lookupGI(name: string): GIEntry | null {
  const lower = name.toLowerCase().trim();

  // 1. Exact match
  if (GI_DATABASE[lower]) return GI_DATABASE[lower];

  // 2. Partial match — input contains key
  for (const [key, val] of Object.entries(GI_DATABASE)) {
    if (lower.includes(key)) return val;
  }

  // 3. Partial match — key contains input
  for (const [key, val] of Object.entries(GI_DATABASE)) {
    if (key.includes(lower) && lower.length > 3) return val;
  }

  // 4. Word-level match — any significant word matches
  const words = lower.split(/\s+/).filter(w => w.length > 3);
  for (const word of words) {
    for (const [key, val] of Object.entries(GI_DATABASE)) {
      if (key.includes(word)) return val;
    }
  }

  return null;
}

// Legacy export for backward compatibility
export const TURKISH_GI_DATA: Record<string, { gi: number; confidence: number; source: string }> = 
  Object.fromEntries(Object.entries(GI_DATABASE).map(([k, v]) => [k, { gi: v.gi, confidence: v.confidence, source: v.source }]));
